### ISSUE TITLE
Code for placing signs

### ISSUE THREAD

**Issue by Neki** [benekastah/neomake#104]
Continuing the discussion in #101:

I am curious about why Neomake needs special handling for placing signs on top while Syntastic does not. 

In both Vim 7.4.52 and Neovim 0.0.0-alpha+201504131721, it seems that the last placed sign appears on top.

Start Neovim with `nvim -u NONE` (with my set of plugins, this also works without the `-u NONE` part) then execute
```
:sign define ex1 text=>>
:sign define ex2 text=<<
```

Go into insert mode, type something on the first line, save the file as `example.txt`, then execute `:sign place 1 name=ex1 line=1 file=example.txt`

I get this:
![image](https://cloud.githubusercontent.com/assets/2143664/7218736/4c51fa3a-e67e-11e4-9cd0-cf01e53eab3b.png)

Then, if I execute
`:sign place 2 name=ex2 line=1 file=example.txt`

I get this:
![image](https://cloud.githubusercontent.com/assets/2143664/7218737/516f0e54-e67e-11e4-9ebb-47d2e1a2ce9b.png)

The new sign has been placed on top. I get the same behaviour with the above version of Vim, with and without sourcing my `.vimrc` file.

`:sign unplace 2` correctly reverts the display to the first image.

gitgutter has special handling for signs: it [parses the output of `:sign place`](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/sign.vim#L70-L107) the same way as neomake, in order [not to place a sign](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter/sign.vim#L152) on a line that already has one. The goal is [not to override signs placed by other plugins](https://github.com/airblade/vim-gitgutter/issues/1). There should be no issue with removing the code that place signs on top (I will try that if I get the time).

**Comment by Neki** [comment]
Seems like it was a bug in neovim: neovim/neovim#1893.

In addition to removing the code that place signs on top, we should also consider removing the code that get the signs in a buffer, since its only use would be ensuring the signs ID are kept unique, something that neither Syntastic nor gitgutter does. Neomake can keep track of the signs it places itself without having to parse the output of `:sign place`.

**Comment by benekastah** [comment]
You were absolutely right. I think that neovim bug was part of the problem, but then somehow the code I had written caused the problem again once the neovim bug was fixed. When I just removed all that code it worked as expected. Thanks for pointing this out!

**Comment by Neki** [comment]
You beat me to it :) Thanks.
