### ISSUE TITLE
The license

### ISSUE THREAD

**Issue by loskutov** [benekastah/neomake#117]
Why not re-license the plugin with some mainstream open-source license? WTFPL is not considered serious by many people (and distros). I guess it would be a nice idea to use e.g. GPL2 or Apache License.

**Comment by dnhgff** [comment]
MIT is probably more apt (if a choice were to be made (i personally find the WTFPL kind of face-palmy, but that's just my own tastes and i don't expect others to share them)) for the spirit intended by WTFPL. it's small and simple to understand and unfettered. GPL and Apache contain a lot of very nuanced legal language with edge cases and honestly who's going to act on any of that withouta big stack of cash to pay a lawyer to know what it actually means in any litigious context (not that i don't think either of those licenses are never appropriate, many projects can make cases for their complexity where it is necessary for their goals, but come on, this is a vim plugin!)

imo WTFPL is fine but it does make me cringe a little :P

**Comment by benekastah** [comment]
I like MIT. Made the change here: 4896868f2308781565118a72f47ebfbe2d20c983
