### ISSUE TITLE
Support for continuous latexmk -pvc

### ISSUE THREAD

**Issue by languitar** [benekastah/neomake#121]
`latexmk -pvc` allows to automatically rebuild a latex file whenever it changes. For this purpose the compiler (and bibtex and so on) are called whenever the file changes and output their usual warning messages on the terminal.

With the support for asynchronous operations in neovim it would be a very nice feature if this continuous compilation mode could somehow be supported in neomake so that whenever latexmk reruns the compilation, new warnings end up as annotations in vim and old ones are deleted.

This probably requires support to process the command output independently of the maker termination and also some kind of pattern needs to be provided to neomake which indicates that compilation has started again, so that old errors can be flushed. Also, it should be possible to terminate latexmk at some point in time...

I am not sure whether this is in the scope of neomake, but it would greatly improve my workflow. Right now I only notice the latex warnings in the latexmk sessions if I actively look at the usually hidden terminal where latexmk runs and filter them out from the whole lot of garbage pdflatex usually prints out.

**Comment by benekastah** [comment]
I'm not against managing continuous jobs like this from neovim, but it seems like it may be a large refactor. It's not on a priority list for me at the moment. That said, if you add a maker for `latexmk` (non-continuous), you could do something like this:

```
autocmd! BufWritePost * Neomake latexmk
```

And every time you save the file from vim, it will rebuild it, which should be an improvement on your current workflow.

**Comment by languitar** [comment]
Right, that makes sense. I briefly tried this already, but the error reporting format for pdflatex such a nightmare that I gave up for the moment.

**Comment by benekastah** [comment]
Let me know if I can help! Unfortunately I didn't find a syntastic make for this, but you may be able to find some other vim plugin that has a good errorformat for latexmk.

**Comment by kazuoteramoto** [comment]
@languitar  Not a errorformat but I use [rubber-info](https://launchpad.net/rubber/) to check errors and warning of a latex run, I think that is much easir to write a errorformat for `rubber-info`. You can also use `rubber` as a latex make in place of latexmk.
Example:
```
$ rubber-info thesis.tex
thesis.tex: [microtype] Unknown slot number of character `\j ' in font encoding `T1' in inheritance list `microtype.cfg/201(protrusion)'. (page 1)
thesis.tex: `h' float specifier changed to `ht'. (page 1)
thesis.tex:954: [hyperref] Token not allowed in a PDF string (PDFDocEncoding): removing `math shift'. (page 5)
thesis.tex:954: [hyperref] Token not allowed in a PDF string (PDFDocEncoding): removing `math shift'. (page 5)
thesis.tex:1128: [hyperref] Token not allowed in a PDF string (PDFDocEncoding): removing `math shift'. (page 5)
thesis.tex:1128: [hyperref] Token not allowed in a PDF string (PDFDocEncoding): removing `math shift'. (page 5)
thesis.sym:25: Overfull \hbox (5434.23953pt too wide) in alignment (page 1)
thesis.sym:25-32: Overfull \hbox (5434.23953pt too wide) in alignment (page 1)
thesis.tex:1132-1133: Overfull \hbox (12.86426pt too wide) (page 5)

```

**Comment by BonarBeavis** [comment]
Is managing continuous jobs still far out? With the `neomake-makers-buffer_output` option it looks like the basics for this are done.

**Comment by blueyed** [comment]
From skimming this only it looks like this should be a maker that keeps running in the background and interacts with Neomake?

**Comment by BonarBeavis** [comment]
Right know Neomake runs the maker and parses the output after the maker finished.
But makers, which watch the files, do not end, they run continuously. Output for sbt in continuous mode looks like this:

```
1. Waiting for source changes... (press enter to interrupt)
[info] Compiling 1 Scala source to /home/beavis/Cloud/work/rdf-crowdsourced-quality-checker/bike-rack-linker/target/scala-2.12/classes ...
[warn] /home/beavis/Cloud/work/rdf-crowdsourced-quality-checker/bike-rack-linker/app/controllers/HomeController.scala:49:38: lazy value parse in trait BodyParsers is deprecated (since 2.6.0): Inject PlayBodyParsers or use AbstractController instead
[warn]   def addTask() = Action(BodyParsers.parse.json).async { request ⇒
[warn]                                      ^
[warn] one warning found
[info] Done compiling.
[success] Total time: 3 s, completed Oct 30, 2017 3:33:30 PM
2. Waiting for source changes... (press enter to interrupt)
[info] Compiling 1 Scala source to /home/beavis/Cloud/work/rdf-crowdsourced-quality-checker/bike-rack-linker/target/scala-2.12/classes ...
[error] /home/beavis/Cloud/work/rdf-crowdsourced-quality-checker/bike-rack-linker/app/controllers/HomeController.scala:59:9: not found: value O
[error]         O(i.body[JsValue])})
[error]         ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 1 s, completed Oct 30, 2017 3:33:48 PM
3. Waiting for source changes... (press enter to interrupt)
```

So Neomake would have to look for the line `Waiting for source changes... (press enter to interrupt)` and then clear the error list and trigger the parsing of the output since the last occurrence of the line.

For java stuff this would be a huge win, starting a new java machine and loading the project for every compile, takes many seconds. This should work  also work for other make programs with file watchers, if the line, Neomake looks for to trigger parsing, could be defined by an errorformat.
