### ISSUE TITLE
Error on Javascript linting

### ISSUE THREAD

**Issue by bronzehedwick** [benekastah/neomake#127]
I am getting the following error when using the Javascript linter on a Nodejs file.
![Errors](http://i.imgur.com/If2dQBP.png)
I am on OS X 10.10.3, and my Neovim version is below.
```
NVIM 0.0.0-alpha+201505080331 (compiled May  8 2015 15:07:18)
Commit: 0d90b5c36c3c17e696792b80f9f4f45778f1cbfd
Build type: RelWithDebInfo
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20150508-8426-kj1ysu/build/config -I/tmp/neovim20150508-8426-kj1ysu/src -I/tmp/neovim20150508-8426-kj1ysu/.deps/usr/include -I/tmp/neovim20150508-8426-kj1ysu/.deps/usr/include -I/tmp/neovim20150508-8426-kj1ysu/.deps/usr/include/luajit-2.0 -I/tmp/neovim20150508-8426-kj1ysu/.deps/usr/include -I/tmp/neovim20150508-8426-kj1ysu/.deps/usr/include -I/tmp/neovim20150508-8426-kj1ysu/.deps/usr/include -I/tmp/neovim20150508-8426-kj1ysu/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim20150508-8426-kj1ysu/build/src/nvim/auto -I/tmp/neovim20150508-8426-kj1ysu/build/include
Compiled by chris@ChristophersMBP

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```
Is this a bug or am I doing something wrong?

**Comment by benekastah** [comment]
What do you see when you run `:set shell?` in neovim? Either you're using an unsupported shell or there is a bug in detecting your shell. The current supported shells can be found [here](https://github.com/benekastah/neomake/blob/master/autoload/neomake/utils.vim#L128)

**Comment by bronzehedwick** [comment]
Ah ha, of course. I'm using `fish`, which isn't on the supported list. I'll see if I can hack on a fix to support fish. Thanks!

**Comment by benekastah** [comment]
Supporting fish shouldn't be too hard. What is the argument used to pass a command? For example, in bash I would do:

```
bash -c 'echo "This is a bash comand"'
```

If you know the equivalent in fish, it would be very easy to add.

**Comment by bronzehedwick** [comment]
It looks like fish also uses `-c` to pass a command. Making a pull request to just add fish to the list.

**Comment by maitriyogin** [comment]
Hi,
I'm using fish and unfortunately get the following when neomake runs eslant :
```
Neomake: [1.-:4:1] Exe (fish: Unsupported use of '&&'. In fish, please use 'COMM
AND; and COMMAND'.^@PATH=$(npm bin):$PATH && which flow^@
^) of maker flow is not executable.
```
Any ideas?
/Stephen.

**Comment by blueyed** [comment]
@maitriyogin 
Looks like `executable('eslant')` produces this for some reason?
Is the exe `eslant` or `flow`?
What exactly are you trying to do?  Please consider creating a new issue with more details, including if you are using Vim or Neovim.
You might fix it by just using something like `set shell=sh` in (Neo)Vim.
