### ISSUE TITLE
Test multiline error messages

### ISSUE THREAD

**Issue by benekastah** [benekastah/neomake#15]
I suspect that multiline error messages will not work currently. We may need to join all lines back into a string with newlines before we feed it to the location/quickfix list. We may also need to gather all errors until the job completes before we populate the list for some checkers.

**Comment by ckafi** [comment]
I currently have this problem with the Kibit Clojure code analyzer. I'm using these settings to parse multiline messages:

    setlocal makeprg=lein\ kibit\ %
    setlocal errorformat=%IAt\ %f:%l:,%C%m,%Z,%-G%.%#
    
    let g:neomake_clojure_kibit_maker = {
        \ 'exe': 'lein',
        \ 'args': ['kibit'],
        \ 'errorformat': '%IAt\ %f:%l:,%C%m,%Z,%-G%.%#',
        \ }
    let g:neomake_clojure_enabled_makers = ['kibit']

Kibits output:

    At test.clj:1:
    Consider using:
      (when true 42)
    instead of:
      (if true 42 nil)

`:make`s output:

    test.clj|1 info|  Consider using: (when true 42) instead of: (if true 42 nil)

`:Neomake`s output:

    test.clj|1 info|  Consider using: (when true 42) instead of:

As you can see, the last line gets lost.

**Comment by benekastah** [comment]
Yup. I did some investigation, and it looks like multiline messages will work fine, as long as the whole message comes through in the same stdout/stderr event. If it gets split across events, it will mess up the parsing of the message. The best solution I can think of is to make a setting to gather all the maker output before trying to put it in the loclist or quickfix list.

**Comment by benekastah** [comment]
This feature should be added in e1bce3d68783a157c8ac16fe15066fd6ca964de1. I'll add docs now, try adding `'buffer_output': 1` to your kibit maker. It should take care of it for you. Let me know if this resolves it.

**Comment by ckafi** [comment]
Works now as expected. Thanks!
