### ISSUE TITLE
Callback on maker exit

### ISSUE THREAD

**Issue by critiqjo** [benekastah/neomake#161]
I'm adding a feature to the plugin I'm working on [lldb.nvim](https://github.com/critiqjo/lldb.nvim) which will allow users to compile their code before launching the debug session. And I want to delegate command handling to Neomake, which will take care of displaying the output asynchronously (in quickfix), displaying error/warning signs etc.

The problem is lldb.nvim can't know when Neomake has completed a command it issued, and its exit status. It needs a callback on exit. So I am working on implementing basic callbacks for Neomake. I will submit a PR when ready.

**Comment by benekastah** [comment]
This sounds like a good idea. I can think of two different callbacks that could be nice to have:

- A callback when an individual maker completes
- A callback when all the makers spawned by the :Neomake command complete.

**Comment by petobens** [comment]
Hi @critiqjo  and @benekastah. Dispatch fires a `QuickFixCmdPost cgetfile` event each time a build finishes. Does neomake do the same? Thanks in advance.

**Comment by critiqjo** [comment]
No, I guess it doesn't. Would that be useful to a user? The only use I can think of is for opening the quickfix window right after it completes... @petobens Do you use that event for anything?

**Comment by petobens** [comment]
Hi @critiqjo. I find it useful because by checking that event I know when Dispatch finishes a build and I can therefore do:

```vim
au QuickFixCmdPost cgetfile call s:SomeRandomFunction()
```
I believe your implementation of exit callbacks generalizes this simple approach?

**Comment by critiqjo** [comment]
Yea, I got that... I was asking if you could provide an example use-case...

Anyway, this is not a generalization of it. Because users won't be able to catch *all* exits.
Only the caller can request a callback. And the caller could be another plugin -- and the user will not be notified by any means. Notifying the user of all events would be another independent feature.

**Comment by petobens** [comment]
I''ll try to provide a concrete a example. Thanks for your explanation.

**Comment by gibiansky** [comment]
Isn't "The only use I can think of is for opening the quickfix window right after it completes..." an example usecase? (I came to this issue trying to do exactly that...)

**Comment by petobens** [comment]
@gibiansky  sorry for the late reply. I also think its valid usecase (at least for me).

**Comment by evindor** [comment]
Ran into that while trying to add neovim support via neomake to https://github.com/wincent/ferret

```
        autocmd QuickfixCmdPost cgetfile call ferret#private#post('qf')
```

**Comment by jamischarles** [comment]
Would love this. Trying to run `eslint --fix` in neomake, but the changes don't show up w/o reloading.

**Comment by jamischarles** [comment]
@benekastah If you can point me to where in the code to add it, I can add a `if g:neomake_reload_file then :e` or something, and issue a PR.

**Comment by beaugunderson** [comment]
I was also looking for a callback for this to jump to the first error in the file (like syntastic can with `let g:syntastic_auto_jump = 3`).

**Comment by edwardsmit** [comment]
@critiqjo @benekastah Can either of you provide a sample how I could use the `exit_callback` to do something useful?
Just like @jamischarles I'd really like to have `:e` called after the `eslint` maker has run.

**Comment by critiqjo** [comment]
You'll have to manually define a command which executes `Neomake#make(1, [], your_func)`. And `your_func` may execute `:e` if [`has_next` is false](https://github.com/benekastah/neomake/blob/master/doc/neomake.txt#L276-281). I'm closing this issue, since it was long resolved.

**Comment by edwardsmit** [comment]
Thank you @critiqjo, if anyone else is interested, I've implemented this here: https://github.com/edwardsmit/dotfiles/blob/master/nvim/settings/neomake.vim

**Comment by bounceme** [comment]
It is best having quickfixcmdPost/Pre working in the plugin i'd say.
