### ISSUE TITLE
Sometimes running neomake can change which buffer is showing in your window

### ISSUE THREAD

**Issue by benekastah** [benekastah/neomake#17]
Particularly when I do `:lopen`, sometimes a subsequent `JobActivity` handler call will switch my file buffer into the loclist buffer. It has to do with the code in the handler that briefly switches back to the original window/buffer you were on when you invoked neomake to process the task.

One potential solution is to only perform this work if the user is in the same window/buffer as they were when they invoked neomake. If they leave that window/buffer, defer the work until they return. Otherwise, we'll just have to make the current switching mechanism more robust.

**Comment by jebaum** [comment]
Just adding a note here, this problem will be much more easily solved when some of the suggestions in neovim/neovim#901 get implemented, particularly something like `bufputlines`

**Comment by benekastah** [comment]
Yes, having functions that operate on a buffer without having to navigate to it would be fantastic. The hacks you have to do to get some of this stuff to work are pretty gross.

**Comment by seven1m** [comment]
Just wanted to chime in this happens to me regularly. Must be my habit of saving a file and switching to another buffer quickly.

I'm hoping there's a fix for this prior to neovim/neovim#901, since that could take awhile.

**Comment by benekastah** [comment]
I have a partial fix for this. It's got a couple of issues of its own I'm trying to work out. Hopefully I'll have a fix soon.

**Comment by seven1m** [comment]
@benekastah++ 100 internet points if you fix this.

**Comment by benekastah** [comment]
Ok, this should be fixed now. I got rid of the fancy window/buffer switching code that I had before, which means that if you want to see the result of `:Neomake`, you need to be in the buffer you started it from. You can leave the buffer; the output of the job(s) will be processed when you come back. It should be noted this restriction doesn't apply to `:Neomake!` (note the exclamation point). If you are in a quickfix window, `:Neomake` will try to process the output for the last window you were in (which does actually require a window switch, but it is much simpler than the last version).

**Comment by Linuus** [comment]
Seems to work great. Thanks @benekastah 

:+1:

**Comment by seven1m** [comment]
Fixed!!!!!

:money_with_wings:
