### ISSUE TITLE
What does Neomake! default to?

### ISSUE THREAD

**Issue by dani-h** [benekastah/neomake#174]
I'm currrently using Neomake with Go. When working on a project with multiple files :Neomake doesn't seem to detect structs and functions in other files than the current file. Neomake! however does, but it builds a binary each time. I'd like to customize the Neomake! command for Go, but I can't seem to find where it's defined in this repo.

**Comment by aliev** [comment]
@dani-h you can use ``set makeprg=`` to use different makers. my example for django ``set makeprg=django-admin\ test`` and I can run Neomake! to run tests for django

**Comment by benekastah** [comment]
Sorry for the wait. @aliev is correct. You can also do `let g:neomake_enabled_makers = ['whatever', 'you', 'want']`.
