### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vito-c** [benekastah/neomake#177]
I am unable to see errors in vimscript. Do I have to have something installed? I was also wondering is Neomake a replacement for syntastic or do they work side by side?

**Comment by benekastah** [comment]
Neomake and syntastic can work side by side if you want, but it is intended to be a replacement. I haven't added a linter for vimscript yet because I have yet to find one that I can get working.

**Comment by vito-c** [comment]
I got vint working which seems to be adequate but a little noisy :)
