### ISSUE TITLE
phpcs output not parsed correctly?

### ISSUE THREAD

**Issue by mikl** [benekastah/neomake#179]
While replacing Syntastic with Neomake, I've run into a small problem regarding the `phpcs` syntax checker – its results are not properly parsed by Neomake.

When Neomake runs, all I get is a meek `Neomake: phpcs complete with exit code 2` in the bottom of the screen, but when I run the same phpcs command as Neomake does (discovered via setting `g:neomake_verbose` to 3), I get a different story:

    ⏚ ⌂208% [mikl:~] % phpcs --report=csv --standard=Drupal --extensions=php,module,inc,install,test,profile,theme /Users/mikl/Work/something/something/repository/themes/neocortex/template.php
    File,Line,Column,Type,Message,Source,Severity,Fixable
    "/Users/mikl/Work/something/something/repository/themes/neocortex/template.php",1,1,error,"Missing file doc comment",Drupal.Commenting.FileComment.Missing,5,1
    "/Users/mikl/Work/something/something/repository/themes/neocortex/template.php",6,4,error,"Missing parameter type",Drupal.Commenting.FunctionComment.MissingParamType,5,0
    "/Users/mikl/Work/something/something/repository/themes/neocortex/template.php",14,3,warning,"There must be no blank line following an inline comment",Drupal.Commenting.InlineComment.SpacingAfter,5,1
    "/Users/mikl/Work/something/something/repository/themes/neocortex/template.php",32,1,warning,"There must be no blank line following an inline comment",Drupal.Commenting.InlineComment.SpacingAfter,5,1
    [and more of the same]

Not sure what goes wrong here, but it seems Neomake has problems parsing the output. I see that the “Fixable” column is not present in the [maker definition file](https://github.com/benekastah/neomake/blob/master/autoload/neomake/makers/ft/php.vim), but I'm not sure if that matters.

**Comment by mikl** [comment]
Hmm, if I remove the ` --extensions=php,module,inc,install,test,profile,theme` (which was injected by appending the string to `g:neomake_php_phpcs_args_standard`), it works just fine.

Apparently, this option is only necessary when running `phpcs` on a folder of files, so it's actually not needed for this case, so leaving it out solves this problem.

**Comment by benekastah** [comment]
Sorry for not responding earlier. Glad you figured it out!
