### ISSUE TITLE
Apply different linters according to syntax

### ISSUE THREAD

**Issue by pwntester** [benekastah/neomake#180]
I'm wondering if there is any way to apply different linters depending on the syntax applied to given chunk of code. For example if an html page embeds a JS script, is it possible to apply an html linter (tidy) and a JS linter (jslint)?

 Thanks

**Comment by benekastah** [comment]
What you're describing is a linter's job, not neomake's. That said, there are two ways I could see this working:

1. Find an html linter that can feed contents of script tags to a javascript linter.
2. Find a javascript linter that can lint javascript inside of html files.

In either case it would be very simple to get those things working in neomake.
