### ISSUE TITLE
Location list populated, but quickfix list not populated

### ISSUE THREAD

**Issue by d-lord** [benekastah/neomake#182]
It's possible this is down to me misunderstanding the purpose of each list.

When editing a .sh file in Neovim and using the default `shellcheck` maker, I'm finding that `:Neomake` will populate the location list (`:lopen`) but not the quickfix list (`:copen`).

As a result, `:cn` reports "E42: No Errors".

Using the location list is fine: output is reported as usual, jumping to lines with <Enter> is as usual, but the quickfix list is empty.

This is true when running `:Neomake` manually or after runs with `autocmd! BufWritePost * Neomake`.

Here's a minimal config displaying this issue:

```
call plug#begin('~/play/.nvim/plugged') " using vim-plug
Plug 'benekastah/neomake'
call plug#end()
```

Is there any debug output that would be useful?
Neovim was compiled today on OSX through Homebrew. `:version` reports:
```
NVIM 0.0.0-alpha+201509190915 (compiled Sep 21 2015 13:26:56)
Commit: 2417aeebbffe58eab6ac39feac0f64a27aafbee2
```

I've tried setting `g:neomake_verbose = 2` but haven't figured out how to read or extract the output yet (one line appears in the command line).

**Comment by towry** [comment]
Same problem here.

**Comment by benekastah** [comment]
There are two basic commands to know about:

- `:Neomake`: operates on a single file. Uses the loclist.
- `:Neomake!`: operates on vim's current directory. Uses the quickfix list. Uses your `makeprg` by default.

I apologize that the difference between these two commands is a simple `!`. That's unfortunate. Something like this may work for you:

```
" Add whatever arguments you need. The % at the end will dump the current filename into the arguments.
set makeprg=shellcheck\ %
```

and then use `:Neomake!` instead of `:Neomake`.

**Comment by d-lord** [comment]
`:Neomake!` does do as expected, thanks for the clear explanation. For any future Googlers, using quickfix:

    set makeprg=shellcheck\ -fgcc\ %
    autocmd! BufWritePost * Neomake!

As it turns out, it's actually better in my context to use `:Neomake` and the loclist. This uses Neomake's makers so everything Just Works, rather than using filetype-specific `makeprg`s.
