### ISSUE TITLE
tslint maker does not work with version 2.5.0

### ISSUE THREAD

**Issue by JDiCode** [benekastah/neomake#185]
tslint version 2.5.0 does not support the -f argument so it exits with an error code but does not update the quickfix list.

**Comment by benekastah** [comment]
Version detection hasn't been implemented yet. I don't use tslint myself, so my preference is that a user of that linter will step in and fix it. If you want to try to fix this issue, the code is [here](https://github.com/benekastah/neomake/blob/master/autoload/neomake/makers/ft/typescript.vim#L20). You can find a way to call it that works with multiple versions, or attempt to detect the version yourself and modify the way tslint is called based on that.
