### ISSUE TITLE
Question: use project .eslintrc if exists, otherwise something else?

### ISSUE THREAD

**Issue by colepeters** [benekastah/neomake#187]
With Synatastic, it’s possible to use eslint with an `.eslintrc` if it exists in the current or parent director(y/ies), and if not, revert to some other linter (e.g. Standard) (see [this issue](https://github.com/scrooloose/syntastic/issues/1484)).

Is this possible to do with Neomake? I’ve read through the docs to check, but to be honest I’m still a little new to customising plugins in Vim/NeoVim.

Thanks in advance!

**Comment by benekastah** [comment]
This just requires a small change to the suggestion in the linked syntastic issue:

```
let g:syntastic_javascript_checkers = []
autocmd FileType javascript let g:neomake_javascript_enabled_makers = findfile('.eslintrc', '.;') !=# '' ? ['eslint'] : []
```

**Comment by colepeters** [comment]
Perfect! Thanks a ton, @benekastah — and for your work on Neomake.

**Comment by benekastah** [comment]
You're welcome :)
