### ISSUE TITLE
Make tsc read tsconfig.json

### ISSUE THREAD

**Issue by HerringtonDarkholme** [benekastah/neomake#200]
TypeScript now accepts a lot of config. I found it hard to pick up one that suits most use case, given that one [popular framework](https://angular.io/docs/js/latest/quickstart.html) adopts aggressive options.

So I create one maker that read tsconfig on the fly.  https://gist.github.com/HerringtonDarkholme/34b57329f04d4ec8df6c

I think this is the most sensible default configuration for neomake. It just works out of box. But it uses ugly json `eval`. 

If you think this is acceptable, I will make a pr.

**Comment by benekastah** [comment]
Hmmm. I'd almost rather create a custom executable for tsc instead. I'm making a few guesses here, but tsc uses nodejs, right? So, if you are running tsc, then you should also be able to run node scripts. Therefore we could have a script like this (pseudo code):

```
#!/usr/bin/env node

var args = [...];
var tsconfig = findFile('tsconfig.json');
var config;
if (tsconfig) {
    config = JSON.parse(readFile(tsconfig));
    for (option in config.compilerOptions) {
        args.push('--' + option, config.compilerOptions[option]);
    }
}

system.execute('tsc', args);
```

This is nice because:

- It doesn't use the potentially unsafe `eval` as a json parser hack.
- It uses tools that tsc users must already have.
- It's not vimscript!

Thoughts?

**Comment by HerringtonDarkholme** [comment]
Yes, it is more robust, and more flexible. The only concern is should we ship this launch script with neomake?

**Comment by benekastah** [comment]
I think that would be ok if the script is kept pretty small (which is probably a good idea anyway).

**Comment by russmatney** [comment]
I ran into this today – any resolution here? I'm curious if there's a way to run the make without specifying a file, and still populate the per-file errors/warnings. Specifying a file voids the tsconfig.json ([docs](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json#using-tsconfigjson)), that's my guess as to why it's not getting picked up. Still toying with it.

**Comment by HerringtonDarkholme** [comment]
I'm closing this issue and recommend users to try tsuquyomi.

After using both neomake and [tsuquyomi](https://github.com/Quramy/tsuquyomi) long enough in my production environment, I have to say comparing neomake and tsuquyomi with regards to error reporting is not fair.

tsuquyomi is specialized for TS, it reports very fast, even in a large project. And, more importantly, it respects project configuration. Every thing works out of box.

Neomake is very good at spotting out errors across various file types, but for TypeScript, the not-so-fast-compiled-language, Neomake cannot perform as well as long running language service like tsuquyomi. 

Though I still miss Neomake's side bar sign, they are so lovely.

**Comment by indiesquidge** [comment]
@HerringtonDarkholme, first of all, thank you so much for mentioning tsuquyomi. I just got hired at a place working on enterprise software written in TypeScript and the app is monolithic. You have no idea how much time I have spent trying to configure my Vim settings and plugins to play nicely with numerous TypeScript files and have them compile correctly, include the right exports, understand namespace, etc. I've gone down so many rabbit holes the last two days its unbelievable.

Anyway, as you just mentioned in your last comment about Neomake's side bar error and warning signs, is there no way to make this a reality with tsuquyomi? Believe me, I'm just happy to finally have my tsc compilation working correctly within Vim, but it would be nice to not have the (obtrusive) Vim quick fix window. If there was a way to show the messages on a line by line basis in the navigation bar and simply have an error symbol on the line that is in question, that would be fantastic. While I do not have nearly enough experience with vim plugin libraries (I can barely get the ones that are already written to work properly, ha!), I would love to figure this out if it's a possibility.

Thanks again though, you saved me from wanting to throw my laptop out the window :)

**Comment by ik9999** [comment]
And if you want to use neomake with tsconfig files[], that's the way for it(its bad though, i believe there is a better one):
* Put this to vimrc
>function! neomake#makers#ft#typescript#tsc()
>    return {
>        \ 'args': [
>            \ '-p', '*PATH TO tsconfig.json directory*', '-m', 'commonjs', '-t', 'es2015', '--noEmit'
>        \ ],
>        \ 'errorformat':
>            \ '%E%f %#(%l\,%c): error %m,' .
>            \ '%E%f %#(%l\,%c): %m,' .
>            \ '%Eerror %m,' .
>            \ '%C%\s%\+%m'
>        \ }
>endfunction

And apply this change:
>diff --git a/autoload/neomake.vim b/autoload/neomake.vim
>index 1928eff..166cdd0 100644
>--- a/autoload/neomake.vim
>+++ b/autoload/neomake.vim
>@@ -75,7 +75,7 @@ function! neomake#MakeJob(maker) abort
> 
>     let args = a:maker.args
>     let append_file = a:maker.file_mode && index(args, '%:p') <= 0 && get(a:maker, 'append_file', 1)
>-    if append_file
>+    if (append_file && a:maker.exe != 'tsc')
>         call add(args, '%:p')
>     endif
>     call map(args, 'expand(v:val)')
