### ISSUE TITLE
The ability to modify default args used by makers without redefinition.

### ISSUE THREAD

**Issue by Earnestly** [benekastah/neomake#203]
Is there a way to append (or replace) custom *args* to the makers without needing to completely redefine it?

For example with syntastic it could be accomplished with `let g:syntastic_cpp_compiler_options = '-std=c++14'`.

**Comment by psychomario** [comment]
I've had some luck with
```
let g:neomake_python_pylint_args = neomake#makers#ft#python#pylint()['args'] + ["-d", "missing-docstring,invalid-name"]

```

Where the array is the arguments you're adding.

**Comment by Earnestly** [comment]
Appending to the end of the array is a possible solution, I'm not sure if that's the best interface but we'll see sooner or later I suppose.

Thanks for the suggestion

**Comment by benekastah** [comment]
Actually you aren't appending to the end of the array. You are creating a new array with `neomake#makers#ft#python#pylint()['args']` as a starting point. You could also do:

```
" Create a list with your custom args at the beginning
let g:neomake_python_pylint_args = ["-d", "missing-docstring,invalid-name"] + neomake#makers#ft#python#pylint()['args']
" Totally override the default args with a list of your own
let g:neomake_python_pylint_args = ["-d", "missing-docstring,invalid-name"]
```

**Comment by s0undt3ch** [comment]
`neomake#makers#ft#python#pylint()['args']` no longer works for me... Unknown function... Got an alternate approach?

**Comment by s0undt3ch** [comment]
Sorry, I was wrong, I was using an old version of neomake apparently
