### ISSUE TITLE
having troubles enabling C++ maker

### ISSUE THREAD

**Issue by esn89** [benekastah/neomake#210]
Right now I am using this:

let g:neomake_cpp_enable_makers = ['clang++']
let g:neomake_cpp_clang_maker = {
     \ 'exe' : 'clang++'
     \ }

to no avail.

Am I missing something here?
This is the error I am getting:  https://i.imgur.com/J8TKwNx.png

**Comment by benekastah** [comment]
Change `clang++` to `clang` and it will work. It will still _execute_ `clang++`. See https://github.com/benekastah/neomake/blob/master/autoload/neomake/makers/ft/cpp.vim#L11

**Comment by esn89** [comment]
i see.  thank you, it worked.  cheers!
