### ISSUE TITLE
Unsettling order of the messages in the loclist

### ISSUE THREAD

**Issue by brunal** [benekastah/neomake#22]
As evoked in issue #21 all checkers get run when Neomake is launched on a file. In syntastic, the checker `n + 1` is only run when the checker `n` reports no problem. This is a behaviour I quite enjoy since it give reports by "layers" of problems. Ideally this behaviour would be configurable (once more I wish I could offer you a PR).

This has a unsettling consequence on the items of the loclist: they appear runner after runner. Having `<tab>` bound as `:lnext`, I expect to go from one issue to another by repeatedly 'tabbing', but many issues shown in the margin will be skipped because they come from a later checker. 'tabbing' will wrap multiple times around the file: once for each checker. This seems kind of strange to me.
Here are the possibilities I see:
1. don't use checkers are one that reported errors (§1)
2. re-order issues according to their line number
3. show errors checker-by-checker. This would imply filling the loclist on demand, seems quite hard to do correctly automatically.

**Comment by benekastah** [comment]
Stopping after the first failing checker won't be possible until neovim adds a feature to get the exit status from a job. See https://github.com/neovim/neovim/issues/1795.

**Comment by benekastah** [comment]
Oh, and do `:help g:neomake_serialize` to learn how to enable the feature.
