### ISSUE TITLE
Setting colour of error / warning signs

### ISSUE THREAD

**Issue by faceleg** [benekastah/neomake#245]
I'd like my warnings to be yellow and my errors to be red - is this possible?

**Comment by chearon** [comment]
Hello, I just did this - it's not in the repo's readme but the details are in `:h neomake`. The options are in section 3, and they are `g:neomake_error_sign` for your errors and `g:neomake_warning_sign` for warnings. You give them an object of what text to use and which highlight group to use. I made a new group to have my warnings be a yellow !:

```VimL
:highlight NeomakeErrorMsg ctermfg=227 ctermbg=237
let g:neomake_warning_sign={'text': '⚠', 'texthl': 'NeomakeErrorMsg'}
```

You'd have to pick the right `guifg` and `guibg` if you're using MacVim.

Here's the full text from the help file:

```
*g:neomake_error_sign* *g:neomake_warning_sign*
These options allow you to control the appearance of the signs that are
placed beside errors and warnings respectively. These are dictionaries that
represent the parameters provided by |sign-define|. Here is an example
definition: >
    let g:neomake_error_sign = {
        \ 'text': 'E>',
        \ 'texthl': 'ErrorMsg',
        \ }
<
See the |:highlight| command to list the highlight groups available to you or
create new ones.
```

**Comment by faceleg** [comment]
Thanks :)

**Comment by faceleg** [comment]
Do you know if there are plans to set some defaults?

**Comment by chearon** [comment]
It was a white ⚠ for me by default, and the errors were an X. maybe you didn't see them because of the font you were using or something

**Comment by faceleg** [comment]
I mean make the default a yellow ⚠ and red x

**Comment by chearon** [comment]
Oh, sorry, yeah I don't know I'm just a random person who stumbled on someone else trying the same thing :grin:

Highlight groups are kind of the job of the color scheme, though, so they may not be able to do that unless they were to link the default to a commonly set highlight group

**Comment by jdhao** [comment]
@chearon , which font support the warning sign ⚠ ? On my computer, this sign is shown as a box.

**Comment by chearon** [comment]
Unless you're on slimmed down Linux you should already have it on your system. You could try installing [this one](https://github.com/MorbZ/OpenSansEmoji). If that doesn't work it might be your terminal.

**Comment by blueyed** [comment]
@jdhao 
Do you also see a box/square here?  ⚠

What terminal are you using?  urxvt might have problems with it (or rather wide unicode symbols in general).
