### ISSUE TITLE
Switching exec for eslint

### ISSUE THREAD

**Issue by ahmedelgabri** [benekastah/neomake#247]
I want to use the local version of eslint `./node_modules/.bin/eslint` instead of the global one and this how my current setup looks like.

```vim
let g:neomake_open_list=2
let g:neomake_javascript_enabled_makers = ['standard']
let g:neomake_jsx_enabled_makers = ['standard']
if findfile('.eslintrc', '.;') !=# ''
  let g:neomake_javascript_enabled_makers = ['eslint']
  let g:neomake_jsx_enabled_makers = ['eslint']
  let g:neomake_javascript_eslint_maker = {
        \ 'exec': $PWD . '/node_modules/.bin/eslint'
        \ }
endif

autocmd! BufWritePost * Neomake
```

But it doesn't look like it's working although if I add `echo($PWD . '/node_modules/.bin/eslint')` the right path gets output. How can I fix this?

**Comment by Yamakaky** [comment]
maybe `neomake_javascript_eslint_maker.bin = $PWD . '/node_modules/.bin/eslint'` or something like that ?

**Comment by ahmedelgabri** [comment]
I don't think `neomake_javascript_eslint_maker.bin` is a valid option?

**Comment by forbesmyester** [comment]
Put this in your .bashrc (or similar) 

$PATH=/node_modules/.bin:$PATH

You'll then realise that you don't ever need to install anything globally, which is a plain silly idea anyway. :smile:

**Comment by ahmedelgabri** [comment]
Any help with this issue?

**Comment by ahmedelgabri** [comment]
Turns out I had a typo! it's `exe` not `exec`, so this works
```vim
  let g:neomake_javascript_eslint_maker = {
  \ 'exe': $PWD .'/node_modules/.bin/eslint'
  \ }
```

But to get _everything_ working you need to do this which I find a bit odd, I'd expect overriding one property to be merged with the other default properties not to override everything.
```vim
  let g:neomake_javascript_eslint_maker = {
  \ 'exe': $PWD .'/node_modules/.bin/eslint',
  \ 'args': ['-f', 'compact'],
  \ 'errorformat': '%E%f: line %l\, col %c\, Error - %m,' .
  \ '%W%f: line %l\, col %c\, Warning - %m'
  \ }
```

**Comment by benjie** [comment]
For anyone else landing on this issue, the correct variable is `g:neomake_javascript_eslint_exe` (omit `_maker`), but to make life easier, I've [made a plugin to do it](https://github.com/benjie/neomake-local-eslint.vim). If you have vim-plug:

```
Plug 'benjie/neomake-local-eslint.vim'
```

**Comment by ahmedelgabri** [comment]
@benjie I fixed my typo and thanks for the `npm-which` script :+1:

**Comment by andrewsuzuki** [comment]
@benjie thanks! extremely helpful

**Comment by gunar** [comment]
There's [a trick I learned](https://github.com/airbnb/javascript/issues/465#issuecomment-173281502), now ported to Neomake:

```vimscript
function! NeomakeESlintChecker()
  let l:npm_bin = ''
  let l:eslint = 'eslint'

  if executable('npm')
    let l:npm_bin = split(system('npm bin'), '\n')[0]
  endif

  if strlen(l:npm_bin) && executable(l:npm_bin . '/eslint')
    let l:eslint = l:npm_bin . '/eslint'
  endif

  let b:neomake_javascript_eslint_exe = l:eslint
endfunction
autocmd FileType javascript :call NeomakeESlintChecker()
 
autocmd! BufWritePost,BufReadPost * Neomake
```
credit to @gcorne.

This works when Neovim is already open, and you open a new .js buffer.

Thank you.

**Comment by benjie** [comment]
That certainly has more safeties than my plugin which is literally just these two lines as an ftplugin:

```VimL
let s:eslint_path = system('PATH=$(npm bin):$PATH && which eslint')
let b:neomake_javascript_eslint_exe = substitute(s:eslint_path, '^\n*\s*\(.\{-}\)\n*\s*$', '\1', '')
```

**Comment by forbesmyester** [comment]
Mine is not part of VIM but safer, more efficient and simpler.

    PATH=$PATH:node_modules/.bin

Which is probably what you want in your shell for normal usage anyway.

Matt

**Comment by gunar** [comment]
@forbesmyester That's neat! If you write it backwards than it'll work even if you have eslint installed globally

    PATH=node_modules/.bin:$PATH

although it won't work if you're in a subdirectory.

I guess one solution would be to add `../node_modules/.bin`, `../../node_modules/.bin`...
but that's ugly. I'm using that vimscript for now.

@benjie yeah you should definitively add it to your plugin :)

**Comment by ahmedelgabri** [comment]
Why not make this function more genetic then, pass a checker and it sets it for you instead of tying it to eslint only.

**Comment by benjie** [comment]
PRs welcome ;)

**Comment by sodiumjoe** [comment]
in case anyone else finds this thread, `npm bin` is really slow and was causing my vim startup time to be longer than i cared for. [This](https://www.npmjs.com/package/npm-which) package is faster, so i'm using @gunar's trick, with an extra check:

```
function! NeomakeESlintChecker()
  let l:npm_bin = ''
  let l:eslint = 'eslint'

  if executable('npm-which')
    let l:eslint = split(system('npm-which eslint'))[0]
    return 0
  endif

  if executable('npm')
    let l:npm_bin = split(system('npm bin'), '\n')[0]
  endif

  if strlen(l:npm_bin) && executable(l:npm_bin . '/eslint')
    let l:eslint = l:npm_bin . '/eslint'
  endif

  let b:neomake_javascript_eslint_exe = l:eslint
endfunction

autocmd FileType javascript :call NeomakeESlintChecker()
```

**Comment by forbesmyester** [comment]
Hi,

Should have got to this sooner but you know GIT can give you the project
dir...

    git rev-parse --show-toplevel

See
http://stackoverflow.com/questions/957928/is-there-a-way-to-get-the-git-root-directory-in-one-command
, there are other options to achieve this in a GIT centric way.

Matt

**Comment by jaawerth** [comment]
Hi all,

Like @sodiumjoe, I found `npm run` to be frustratingly slow, but I didn't want to have any external/global npm dependencies, so I more or less re-implemented it vimscript, in an [autoloaded function](https://github.com/jaawerth/nrun.vim/blob/master/autoload/nrun.vim#L22-L48) to get the same behavior. It struck me that this could come in handy elsewhere, so I made it into a little plugin: [jaawerth/nrun.vim](https://github.com/jaawerth/nrun.vim). I'm new to vimscript, so critiques, PR's, etc are welcome!

I'm using it like this:
```vimscript
let g:neomake_javascript_eslint_exe = nrun#Which('eslint')
let g:neomake_javascript_enabled_makers = ['eslint']

autocmd! BufWritePost * Neomake
autocmd! BufWinEnter * Neomake
```

For portability I went ahead and rolled all of the above  into a single ftplugin [here](https://github.com/jaawerth/neomake-local-eslint-first)

**Comment by benjie** [comment]
@jaawerth Because you're doing `let g:` it's setting the option globally; you probably only want it buffer based (so different projects can use different versions of eslint), via `let b:` - e.g. https://github.com/benjie/neomake-local-eslint.vim/blob/master/ftplugin/javascript.vim

**Comment by jaawerth** [comment]
@benjie Ah, great point. Updated. I've also stopped setting the eslint makers and removed the `autocmd`, since it makes more sense to set that elsewhere.

**Comment by siemiatj** [comment]
@jaawerth Can you comment on where to set `autocomd` ?

**Comment by balaclark** [comment]
@jaawerth excellent plugin, thanks!

**Comment by jaawerth** [comment]
@siemiatj - Sorry for the delayed response there, guess I missed a notification! Anyway, I'm no expert on best practices here, but for the sake of avoiding overrides where possible and separating functionality from settings, if you're going for reusability it can be better to put the autocmd stuff either in `init.vim` itself, or in a designated file to source for all your JS/linting/whatever functionality needs. Though it's not really a big deal for the ftplugin itself, depending on how widespread it's supposed to be used.

@balaclark - No problem - please feel free to leave feedback and/or PRs if you find anything missing or broken!

**Comment by simonsmith** [comment]
@jaawerth You've made my nvim super snappy again. Thanks!

**Comment by blueyed** [comment]
@simonsmith 
Please elaborate on what helped you.
It should be fixed in the core.

**Comment by sodiumjoe** [comment]
@blueyed don't think it's an issue with neomake ultimately. The problem the above plugin solves is that a project depends on a specific version of `eslint`, and you can have both a project-local and global installation of the `eslint` bin. The plugin checks local first, then traverses up to find the global as a fallback.

**Comment by jaawerth** [comment]
@blueyed - [nrun.vim](https://github.com/jaawerth/nrun.vim) is a small plugin that contains a pure vimscript native implementation of what `npm bin` does + `which` behavior. It's a lot faster because npm's CLI commands all come with a small but frustratingly noticeable delay due to how npm loads its configuration when called. It's inspired by this thread, but I find it useful for more than just Neomake, since it's a node best practice to use the locally-installed version of most node-based dev/build tools to avoid version conflicts and the like.

It's basically just [this function](https://github.com/jaawerth/nrun.vim/blob/master/autoload/nrun.vim#L16-L60) - I'd be more than happy to submit a PR if you'd like!

**Comment by blueyed** [comment]
@jaawerth 
I do not grasp the issue fully, but it sounds good in general: please go ahead with a new PR/issue.

**Comment by jaawerth** [comment]
@blueyed - Sorry for the delayed response, but will do! In a vacuum my first instinct would be to make the local project fallback the default behavior and let people override it as needed e.g. `let g:neomake_javascript_eslint_exe = 'eslint'`, but for the sake of not making breaking changes to Neomake, would you prefer I add it as an optional behavior behind a flag?

__A little more background if you're interested__
CLI tools used in the build process for a project can have a number of versions with compatible plugins, config syntax, etc, and a differing versions can lead to false errors or a failure to build entirely, so it's a best practice to add them as devdeps in `package.json`, which locks them into a compatible `semver` version. This allows a dev to clone a project and get the full build environment running with a simple `npm install` without having to hunt for and manually install a missing tool. This can happen with any of the node-based linting/build tools available in Neomake; eslint, jscs, scss-/style/csslint, tsc, tslint, coffeelint, etc, and to my knowledge defaulting to a local version won't break of any these tools.

For example, `eslint` only looks for plugins and config presets relative to its install location, so if a project is configured to use `eslint-plugin-react` or the popular styleguide `eslint-config-airbnb`, a global exe will fail to find it, bail on the whole process, and throw an error.

**Comment by blueyed** [comment]
@jaawerth 
Hmm, as for my Python virtualenvs, I rely on $PATH/$VIRTUAL_ENV mostly..
For other cases https://github.com/embear/vim-localvimrc comes in handy, where you could set `*_exe`.
But I can see that this is cumbersome in general.

What about a generic function to handle this (like Syntastic) has, and then use it in makers where it is relevant?  Might also be some flag on the maker then.

Would be nice to create a new issue with some plan, or a PR right away.

**Comment by jaawerth** [comment]
Sure thing; I already have a generic function in my little nrun plugin, just need to integrate it, so a quick PR it is!

**Comment by felix-d** [comment]
I case somebody uses [vim-rooter](https://github.com/airblade/vim-rooter) and wants to change the  executable path dynamically after vim-rooter has changed the current working directory.

`vim-rooter` uses `BufEnter` and the autocommand that calls `:Rooter` is normally called after any `BufEnter` you specify in your vim config, so you need to use `BufWinEnter` to not have to redefine `vim-rooter` behaviour manually, for it to be called *after* the directory has changed.

```vim
au BufWinEnter *.rb :let b:neomake_ruby_rubocop_exe =  system('PATH=$(pwd)/bin:$PATH && which rubocop | tr -d "\n"')
```

Also note that `autocmd BufReadPost * Neomake` won't work, since `BufReadPost` is called before vim-rooter has changed the directory. Again, a workaround would be to use `BufWinEnter` instead. Note that this `BufWinEnter` statement needs to be defined *after* the one that changes the executable path.

**Comment by notantonia** [comment]
Now that there's [npx](https://www.npmjs.com/package/npx), should this be used instead?

**Comment by benjie** [comment]
If you do; make sure you pass the `--no-install` flag!

**Comment by benjie** [comment]
The advantage to doing this on a per-file basis is the cost is only incurred once at the start and then we run the binary directly from then onwards for that file. With `npx` the binary search will take place every execution which may add a slight increase to latency (especially to people running on spinning rust rather than SSDs). It might be a good default though, so long as it has an escape hatch?

**Comment by notantonia** [comment]
I'm not sure about an escape hatch, but I think it would be a good default for any npm linters since it's usually recommended to install locally rather than globally and this would mean neomake would work out of the box for everyone.

**Comment by davidosomething** [comment]
For anyone still interested, I've configured some of my makers to use `npx`

here's the config, though you'll have to deconstruct it for your own use

Helper function: https://github.com/davidosomething/dotfiles/blob/master/vim/autoload/dkoproject/neomake.vim#L68

Setup: https://github.com/davidosomething/dotfiles/blob/master/vim/autoload/dkoproject/neomake/javascript.vim#L7

**Comment by blueyed** [comment]
Maybe it is worth adding something to the documentation/FAQ then?
ALE has an option to look for makers/linters in node_modules, but I still think that you should rather "just" configure your `$PATH` correctly, similar to Python, where you add the `bin` of your virtualenv to the `$PATH`.
