### ISSUE TITLE
E417: missing argument: guibg= when sourcing neomake.vim

### ISSUE THREAD

**Issue by eyalfir** [benekastah/neomake#259]
Got this error when running the plugin:
```
Error detected while processing /Users/user/.config/nvim/plugged/neomake/plugin/neomake.vim:
line   48:
E417: missing argument: guibg=
line   49:
E417: missing argument: guibg=
line   50:
E417: missing argument: guibg=
line   51:
E417: missing argument: guibg=
```

This was introduced in commit 2a723d7307b8ef47f29e5372633c89f0bea69289 (@eugen0329)

The cause is this line:
```
 " guibg=" . synIDattr(synIDtrans(hlID("SignColumn")), "bg", "gui")
```
Which evaluates to:
```
guibg=
```
When this is passed to `hi` the exception occurs.

I removed this line, leaving only 
```
let s:sign_bg =
            \ " ctermbg=".synIDattr(synIDtrans(hlID("SignColumn")), "bg", "cterm")
```

And everything seems to be working.

**Comment by luxflux** [comment]
I also get this... Did you find a solution @eyalfir?

**Comment by eyalfir** [comment]
No, but didn't look very hard. Removing the `guibg=` part solved it without any noticeable effect on the bg color of the gutter.

**Comment by benekastah** [comment]
I reverted #248, so this should be fixed.
