### ISSUE TITLE
Add support for shellcheck

### ISSUE THREAD

**Issue by danihodovic** [benekastah/neomake#266]
https://github.com/koalaman/shellcheck

**Comment by sbdchd** [comment]
I believe shellcheck is already used by neomake.

see: https://github.com/benekastah/neomake/blob/dc65a7a5d85670c84fc0055d19fa6901ae96ef93/autoload/neomake/makers/ft/sh.vim

**Comment by danihodovic** [comment]
You are correct. My bad
