### ISSUE TITLE
rust maker parameter causes wrong error report

### ISSUE THREAD

**Issue by zekzekus** [benekastah/neomake#275]
when i open my rust source files with neovim, neomake usually have an error on first line if there is an extern crate statement. 

i checked sytastic plugins syntax_checker for rust programs and it uses `-Z parse-only` and does not raise warning for the extern crate lines. 

neomake rust makes does not use this parse-only argument but using `-Z no-trans`. when i checked descriptions for these params: 

```
    -Z                   parse-only -- parse only; do not compile, assemble, or link
    -Z                     no-trans -- run all passes except translation; no output
```

i think to use parse-only for rust make is a better idea.

**Comment by zekzekus** [comment]
please check #276

**Comment by jonhoo** [comment]
A better long-term solution would probably be to use the rust.vim [syntax checker definition](https://github.com/rust-lang/rust.vim/blob/master/syntax_checkers/rust/rustc.vim) like syntastic does. That way, we don't have to maintain on of our own.
