### ISSUE TITLE
Silence completion message for Neovim

### ISSUE THREAD

**Issue by indiesquidge** [benekastah/neomake#277]
Hi there,

Up front I just want to say how awesome I think this plugin is. I have enjoyed using it from the moment I switched over to Neovim.

I have a question about silencing the completion message that is output on save for each file in the vim command bar. For example, when I save an `html` file I may see

```sh
Neomake: tidy complete with exit code 2
```

What I would like to do is not show this message. I would instead like to see the file path.

I can achieve this by manually commenting out the completion report `if` block directly in the source code of my installed version of `Neomake`

```vim
if has('nvim')
    " Only report completion for neovim, since it is asynchronous
    call neomake#utils#QuietMessage(get(maker, 'name', 'make').
        \ ' complete with exit code '.status)
endif
```

However, it feels icky to comment out a source file for a plugin (obviously). I was hoping that there was just an API interface to configure this on `Neomake`. I see that the function to show the message is called `neomake#utils#QuietMessage`, so in my `.vimrc` I tried writing things like

```vim
let g:neomake#utils#QuietMessage=0
```
or
```vim
let g:neomake#utils#QuietMessage=""
```
and so on, but that doesn't seem to be changing anything. I am fairly new to understanding how VimL is even written, so understanding how to set function calls, what is public and what is private, etc. is still a learning process for me.

I would appreciate any help you can give, thank you :)

**Comment by euoia** [comment]
@indiesquidge I think you can silence these messages with:

```
let g:neomake_verbose = 0
```

If you look at the definition of `neomake#utils#LogMessage` you can see there's a check with a log level, with the default log level being 1.
