### ISSUE TITLE
Running a check without saving

### ISSUE THREAD

**Issue by dpavlic** [benekastah/neomake#28]
Is there any possibility of running a check without saving the file? In other words, :Neomake runs the checks on the current buffer in its current state, rather than the last write?

I understand what I am asking for might not be feasible and that the file needs to be saved before it is checked depending on the checker: but maybe a possibility to specify a directory where a temporary file could be copied with the current buffer state, then deleted, and any errors reported in the buffer worked on.

This would be very useful since it would enable me to Neomake the buffer every time I, for example, enter the normal mode, without at the same time seting the buffer to autowrite every time I enter the normal mode.

**Comment by benekastah** [comment]
Just merged this. I still get temp files that don't get cleaned up from time to time; not sure why that happens. But it is a minor enough issue, and not everyone will use this feature.

**Comment by benekastah** [comment]
Also: do `:help g:neomake_make_modified` to see the docs for this feature.

**Comment by dpavlic** [comment]
Thanks a million for this implementation. It works great for my purposes.

**Comment by benekastah** [comment]
No problem! I forgot to add one note: if you are running `:Neomake` pretty frequently, you might want to set `g:neomake_verbose` to 0. When I didn't do that, my screen would sometimes shift upward if two messages happened to get displayed in close succession.

**Comment by greyblake** [comment]
@dpavlic , @benekastah 

Hi, sorry guys for disturbing you.
I can't make this work. I've added to my nvimrc:
```vim
let g:neomake_make_modified=1
autocmd! BufWritePost * Neomake
```

Add I get error message when I save a file, but not when I change a buffer. 
Did I misunderstand the feature or do I do something wrong?
Thanks in advance.

**Comment by benekastah** [comment]
The issue is that the BufWritePost event only fires after saving. You need to use a different event like InsertLeave or something similar. You may still have problems because not all checkers support this feature. For that reason we are considering removing this feature.

**Comment by greyblake** [comment]
@benekastah  thanks for the reply! 
I've tried to use jobcontrol to trigger `Neomake` every second like this (the implementation is not the best one)

```vim
function s:JobHandler(job_id, data, event)
  Neomake
endfunction

let s:callbacks = {'on_stdout': function('s:JobHandler') }
call jobstart(['bash', '-c', 'while true; do sleep 1; echo test; done'], s:callbacks))
```

But looks like it's quite annoying)  Anyway I am really excited about the Neovim and all functionality it brings us. 

Thanks for the amazing plugin and the job you've done!

**Comment by greyblake** [comment]
Yea, looks like `InsertLeave` is better solution)

**Comment by Neki** [comment]
@greyblade `g:neomake_make_modified` was removed in #84, so when you update Neomake this will no longer work.

**Comment by blueyed** [comment]
See https://github.com/neomake/neomake/pull/1057 for bringing it back.
It is very much required for autolinting in insert mode, that's why I am pushing it.
