### ISSUE TITLE
Error detected while processing function neomake#MakeHandler

### ISSUE THREAD

**Issue by Alok** [benekastah/neomake#285]
I have the linters `ghc-mod`, `hvdevtools`, and `hlint` enabled for Haskell.

I'm using the autocommand `autocmd! BufEnter,BufWritePost * Neomake`.

I get the following error every time I write a haskell file.

`Error detected while processing function neomake#MakeHandler:
line   98:
E119: Not enough arguments for function: neomake#Make`

**Comment by FuzzOli87** [comment]
I'm getting this same error with eslint.

Setting:
``` autocmd! BufWritePost * Neomake ```

It only seems to happen when I make changes to different files opened in different split buffers and I do a ``` :wa ``` It does not happen if I save each file individually.

**Comment by megalithic** [comment]
Having this same issue with standardjs linting of newly opened JS files, however, no issues when opening a JSX file. E.g. a JavaScript file with jsx contained there-in. Both files contain es2015/2016 syntax. Latest HEAD on neovim, and latest for neomake as well (just ran `:PlugUpdate` via vim-plug).

**Comment by megalithic** [comment]
@benekastah any thoughts around this one?

**Comment by FuzzOli87** [comment]
@megalithic Is it always for every file? Or does it happen when you try to save multiple files, that are open, at the same time?

**Comment by megalithic** [comment]
@FuzzOli87 so far, has been any individual file (specifically JS/JSX). I don't typically `:wall`, as I'm typically saving individual files.

**Comment by FuzzOli87** [comment]
@megalithic That is odd. I don't get it to reproduce in any other way besides doing changes in two files and ```:wa``` I've opened JSX/JS files as well individually and as long as I save it by itself it works as expected. I wonder what else is going on...

Do you mind sharing your nvimrc?

**Comment by megalithic** [comment]
@FuzzOli87 sure thing: https://github.com/megalithic/dotfiles/blob/master/vim/vimrc.symlink

**Comment by xanderdunn** [comment]
I have exactly the same issue.  It popped up only a couple of days ago when I updated my Neomake plugin.  

Often, after Neomake is called in my Python files, I get this error:
```
Neomake: pylint complete with exit code 2
Error detected while processing function neomake#MakeHandler:
line   98:
E119: Not enough arguments for function: neomake#Make
Press ENTER or type command to continue
```

I have it set to be called automatically:
```
set updatetime=4000
autocmd FileType python,cpp,scala,objc,swift,julia autocmd TextChanged,InsertLeave <buffer> call FormatAndCheck()

function! FormatAndCheck()
        :silent! :Neomake
endfunction
```

For me it is unrelated to saving the file and actually occurs when `Neomake` is called.

**Comment by davidgranstrom** [comment]
This happens to me as well, but only when `:Neomake` is called using an autocmd. 
If I roll back to 9ad044b the issue disappears.

    autocmd BufWrite *.js Neomake
    autocmd InsertLeave *.js Neomake

**Comment by derekprior** [comment]
I see this issue particularly for longer-running linters. If I write a file then immediately switch buffers, it seems like when the linter completes it throws this error. If I stay in the buffer and wait for the linter to complete everything is just fine.

**Comment by vito-c** [comment]
Possibly related: https://github.com/benekastah/neomake/issues/291

**Comment by Alok** [comment]
One of the recent updates fixed this, thanks.
