### ISSUE TITLE
Not enough arguments for function: neomake#Make

### ISSUE THREAD

**Issue by gunar** [benekastah/neomake#291]
Once in a while I get this error:

![neomake](https://cloud.githubusercontent.com/assets/7684574/12624046/1d0b9e64-c514-11e5-97bf-b084c30a9f11.png)

I'm using

```vimscript
let g:neomake_javascript_enabled_makers = ['eslint']
autocmd! BufWritePost * Neomake
```

This occurs when I'm using [vim-auto-save](https://github.com/vim-scripts/vim-auto-save). Still, with disabled, I'm able to reproduce the error:

1. Open .js file
2. Cause an error (remove a comma or something)
3. Run `:undo | w | redo | w`.

Thank you for your time.

**Comment by johnfraney** [comment]
I'm getting the same error with my Python files:
```
Neomake: pylint complete with exit code 0                                                                                             
Error detected while processing function neomake#MakeHandler:                                                                         
line   98:                                                                                                                            
E119: Not enough arguments for function: neomake#Make
```

I'm using

```
autocmd BufReadPost,BufWritePost * Neomake
let g:neomake_airline = 0
```

I just updated to the most recent version of NeoMake today.

**Comment by iclanzan** [comment]
I am getting the same error and also using just `eslint`. The error can be easily triggered by saving twice in quick succession or switching tabs.

**Comment by benbarbour** [comment]
Ditto for python

**Comment by johnfraney** [comment]
It doesn't appear to be a language-specific issue since the error occurs even when `:Neomake` is called in a new buffer.

**Comment by epilande** [comment]
I'm receiving the same error with eslint. Any word on this?

**Comment by modulesio** [comment]
I can also reproduce this pretty easily by saving a couple of times in a short period (< 1 second). Then this error pops up and eats the next keystroke unexpectedly.

**Comment by compressed** [comment]
I'm also getting this error once I set `let g:neomake_serialize = 1` with two different makers.

**Comment by callmevlad** [comment]
@benekastah Hey Paul, dinner on me anywhere in SF if we can get this looked at :grimacing:

**Comment by danihodovic** [comment]
Same for jscs

**Comment by hauleth** [comment]
Ruby also

**Comment by s0undt3ch** [comment]
Dam, why did I update...

**Comment by s0undt3ch** [comment]
https://github.com/benekastah/neomake/commit/5888211c7ccea0d1d62b621450d5862633cf6651 !?

**Comment by s0undt3ch** [comment]
Yep, pinning to that specific commit allows me to keep using it.

**Comment by martin-svk** [comment]
Do we know where the problem is?

**Comment by ik9999** [comment]
Same error with Eslint+Javascript.
>Error detected while processing function neomake#MakeHandler:                                                                                                                                                                       
>line   98:                                                                                                                                                                                                      
>E119: Not enough arguments for function: neomake#Make`

**Comment by hauleth** [comment]
I think (untested) that this should do:

```diff
diff --git a/autoload/neomake.vim b/autoload/neomake.vim
index 1928eff..843646f 100644
--- a/autoload/neomake.vim
+++ b/autoload/neomake.vim
@@ -534,7 +534,7 @@ function! neomake#MakeHandler(job_id, data, event_type) abort
                 call neomake#utils#LoudMessage('Aborting next makers '.next_makers)
             else
                 call neomake#utils#DebugMessage('next makers '.next_makers)
-                call neomake#Make(maker.next)
+                call s:Make(maker.next)
             endif
         endif
     endif
```

**Comment by gunar** [comment]
Seems to work for me. I'll report in case of any problems.

**Comment by ik9999** [comment]
Works correctly with @hauleth's fix.
Thank you, @hauleth.
