### ISSUE TITLE
ESLint stdout not show in either location list or quickfix

### ISSUE THREAD

**Issue by theamazingfedex** [benekastah/neomake#296]
## The Issue: ##
I switched over to Neomake because Syntastic was taking too long to execute on large JS files, and the speed of Neomake is awesome, although it would be even cooler if I could get it to show me the results.

I uninstalled Syntastic, and installed Neomake using NeoBundle prior to trying all of this.

When I run `Neomake` from a buffer with one of my JS files, the vim command line (the place that I entered the `Neomake` command) flashes through some text extremely quickly, and then stops at `Neomake: File-level errors cleaned in buffer 1`. After this, there is nothing shown in either the `:lopen` or `:copen` lists, nor is there anything in the gutter saying where errors are happening.

After getting this, I checked the `:messages` of vim and noticed that everything that ESLint had found, was hanging out in there. To try and debug a bit more, I also configured Neomake to log out to a file, and found almost the exact same thing there as in messages; all of my eslint output.

Has anyone had this sort of issue switching from Syntastic to Neomake? If so, what were some steps to fix it? I've not been able to find anything on the googles about eslint stdout not being read by Neomake.

## Neomake.log ##
2016-02-02T16:32:26-0700 Log level 2: Neomake: Starting: /mnt/Resources/Workspace/one-exchange/node_modules/.bin/eslint --no-color /mnt/Resources/Workspace/one-exchange/webpack.config.js
2016-02-02T16:32:27-0700 Log level 3: Neomake: eslint stdout: 
2016-02-02T16:32:27-0700 Log level 3: Neomake: eslint stdout: /mnt/Resources/Workspace/one-exchange/webpack.config.js
2016-02-02T16:32:27-0700 Log level 3: Neomake: eslint stdout:   21:3   warning  Unexpected console statement  no-console
2016-02-02T16:32:27-0700 Log level 3: Neomake: eslint stdout:   21:15  warning  Strings must use singlequote  quotes
2016-02-02T16:32:27-0700 Log level 3: Neomake: eslint stdout: 
2016-02-02T16:32:27-0700 Log level 3: Neomake: eslint stdout: ✖ 2 problems (0 errors, 2 warnings)
2016-02-02T16:32:27-0700 Log level 3: Neomake: eslint stdout: 
2016-02-02T16:32:27-0700 Log level 3: Neomake: eslint stdout: 
2016-02-02T16:32:27-0700 Log level 3: Neomake: eslint stdout done.
2016-02-02T16:32:27-0700 Log level 3: Neomake: eslint processing 8 lines of output
2016-02-02T16:32:27-0700 Log level 1: Neomake: eslint complete with exit code 0
2016-02-02T16:32:27-0700 Log level 3: Neomake: File-level errors cleaned in buffer 1

## Relative .vimrc settings ##
let g:neomake_javascript_eslint_exe='/path/to/eslint'
let g:neomake_verbose=3
let g:neomake_open_list=2
let g:neomake_list_height=20
let g:neomake_javascript_eslint_maker = {
      \ 'args': ['--no-color'],
      \ 'errorFormat': '%f: line %l\, col %c\, %m',
      \ }
let g:neomake_javascript_enabled_makers = ['eslint']
let g:neomake_logfile='/mnt/Resources/Workspace/neomake.log'
let g:neomake_warning_sign = {
  \ 'text': 'W',
  \ 'texthl': 'WarningMsg',
  \ }

let g:neomake_error_sign = {
  \ 'text': 'E',
  \ 'texthl': 'ErrorMsg',
  \ }

**Comment by nightire** [comment]
Seems like ESLint change its CLI options' syntax recently?

Here's a working configuration, with ESLint v1.10.3:

```viml
let g:neomake_javascript_enabled_makers = ['eslint']
let g:neomake_javascript_eslint_maker = {
      \ 'args': ['--no-color', '--format', 'compact'],
      \ 'errorformat': '%f: line %l\, col %c\, %m'
      \ }
```

Neomake's default configuration for ESLint has some errors, you have to specify the right CLI options

**Comment by Morantron** [comment]
Same is happening to me :_

**Comment by theamazingfedex** [comment]
I received a response to this issue through github via email from an *Albert Yu*, and it seemed to solve the issue I was having: 

> Seems like ESLint change its CLI options' syntax recently?
> 
> Here's a working configuration, with ESLint v1.10.3:
> 
> let g:neomake_javascript_enabled_makers = ['eslint']
> let g:neomake_javascript_eslint_maker = {
>       \ 'args': ['--no-color', '--format', 'compact'],
>       \ 'errorformat': '%f: line %l\, col %c\, %m'
>       \ }
> Neomake's default configuration for ESLint has some errors, you have to specify the right CLI options

**Comment by theamazingfedex** [comment]
Perhaps @benekastah could update this plugin to work with the changed eslint options?

**Comment by evanharmon** [comment]
Taking out 'compact' from the args worked for me.
```
let g:neomake_javascript_eslint_maker = {
			\ 'args': ['--no-color', '--format'],
			\ 'errorformat': '%f: line %l\, col %c\, %m'
			\ }
```

**Comment by Morantron** [comment]
```
  let g:neomake_javascript_enabled_makers = ['eslint']
  autocmd BufWritePost * Neomake
```

This configuration *just works* :tm: for me

**Comment by theamazingfedex** [comment]
So it seems after looking through the source that Eslint is a built-in maker for Neomake, so any defining of the neomake_javascript_eslint_maker is redundant, unless you need to see your errors in a specific format. Also, in neovim.vim, there is a call to an out-dated function, which causes it to fail whenever trying to run makers. PR #298 updated that function call, and got me working again.

**Comment by colepeters** [comment]
I’m also experiencing this issue, though none of the fixes here have worked for me — no error/warning signs or output in quickfix or location list. I do get a statusline update about Neomake’s exit code, but that’s it.

**Comment by theamazingfedex** [comment]
@colepeters 
1. Did you try the fix suggested in #298? 
2. Are there any messages from Neomake in your `:messages` output?

**Comment by colepeters** [comment]
@theamazingfedex Thanks for this — I tried installing Neomake from @hauleth’s fork (#298) and it works perfectly. Hoping @benekastah can merge this fix in soon; in the mean time I’ll keep using @hauleth’s fork.

**Comment by colepeters** [comment]
@theamazingfedex Are you still interested to see a `neomake.log` if #298 is working for me?

**Comment by ddelnano** [comment]
I am experiencing this issue with eslint and jscs.  I just installed neomake today meaning I have that fix from #298.  When setting `g:neomake_verbose = 3`.  It shows that my linters are running correctly and picking up errors.  However, running :lopen or :copen reveals no errors.

Anyone have any other suggestions on how to fix this???

Here is the output I am getting when running neomake.
<img width="1317" alt="screen shot 2016-02-28 at 5 39 46 pm" src="https://cloud.githubusercontent.com/assets/5855593/13382424/4e733f2e-de42-11e5-93dc-15ea23e92a2d.png">

**Comment by theamazingfedex** [comment]
@ddelnano Can you post your minimal.vimrc in here? Just showing which neomake options you are using, and how you have them configured.
Also, which linter are you trying to use, JSCS or Eslint?

**Comment by ddelnano** [comment]
I was actually able to get it to work but only if I use globally installed eslint and jscs

**Comment by ddelnano** [comment]
My config is all on github [here](https://github.com/ddelnano/dotfiles), not exactly minimal.  I was trying to override just the executable and not the error formatting so I think what was happening is that no errors were reported cause I didn't specify a format.  Need to try overriding all of it later tonight.

**Comment by theamazingfedex** [comment]
@ddelnano Ah, well I don't feel like trying to wade through your .vimrc, so if you can make a gist, or just paste into here, the settings you have that pertain to neomake, we might be able to figure out what's causing that. I'm still curious though, why are you using both JSCS and ESLint?

**Comment by ddelnano** [comment]
Yea I wasn't expecting you to lol. I will try a minimal config with it set locally, which is where I was having problems. And for the projects we use where I work that is what we use. I was given the .eslintrc and .jscs file for the project since that's what we use for all our node peojects

**Comment by theamazingfedex** [comment]
@ddelnano 
If you want to run multiple checkers, make sure that you have 
`let neomake_javascript_enabled_makers = ['eslint', 'jscs']`.
What I do to make sure that I'm using my locally installed eslint, is this: 
`let g:eslint_path = system('PATH=$(npm bin):$PATH && which eslint')`
 which loads the local npm bin onto the PATH, and asks for the path to the eslint exe, which if you have one locally, it will find first, and if not, it will default to a global installation.
And then:
`let g:neomake_javascript_eslint_exe=substitute(g:eslint_path, '^\n*\s*\(.\{-}\)\n*\s*$', '\1', '')`
loads that path into something neomake likes and sets the executable.

My suggestion for you, would be to do these things for both your eslint and jscs installs (just copy, paste, and change eslint to jscs.)

**Comment by ddelnano** [comment]
ah nice I will try this tonight I was busy yesterday one problem I am having though is the location list window popping up and down like this

![neomake](https://cloud.githubusercontent.com/assets/5855593/13435404/2341ba12-dfa8-11e5-9df0-7b1e765dc587.gif)

Have you ever had this issue?

Seems to happen when my jscs detects whitespace, which is what I did to force the video I posted.

**Comment by theamazingfedex** [comment]
That looks like it's running neomake on each change. I set mine to only run when I enter the buffer or save the buffer to reduce background calls and visual noise like this, which might be something you'd want to do as well.

Here's how I do it:
```vim
augroup neomake
  au! BufEnter *.js call EnterNeomake()
  au! BufWritePost *.js call SaveNeomake()
augroup END
function! EnterNeomake()
  " don't show the location-list when entering a buffer
  let g:neomake_open_list=0
  exe "Neomake"
endfunction
function! SaveNeomake()
  " show the loc-list after saving
  let g:neomake_open_list=2
  exe "Neomake"
endfunction
```

**Comment by ddelnano** [comment]
What do you mean on each change? That is just one save and my config is to run it on BufEnter and BufWritePost

**Comment by ddelnano** [comment]
If the window has focus it seems to do that. But only on white space errors, as far as I know

**Comment by theamazingfedex** [comment]
Oh. Wow, that's just one save, that's crazy. I'm not really sure then, though I think this warrants opening a separate issue. I'll continue to see if I can help, but I strongly suggest making a new issue, as this has deviated from the original issue.

**Comment by theamazingfedex** [comment]
This issue was resolved by #298

**Comment by ddelnano** [comment]
Yea sorry about that I will create a new issue.

**Comment by theamazingfedex** [comment]
For future reference, ddelnano's issue was moved to #323

**Comment by thornycrackers** [comment]
@theamazingfedex, You mentioned that 'Eslint is a built-in maker for Neomake', is this still the case? Right now I'm experiencing a similar issue to the original. I'm trying to use a globally installed eslint and also trying to pass '--config ~/.eslintrc'  in the args. When I set verbose to 3 in my init.vim and check my messages this is what I'm getting:

`
Neomake: Starting: eslint --config ~/.eslintrc.json /path/to/app.js
Neomake: eslint stdout: eslint [options] file.js [file.js] [dir]
Neomake: eslint stdout:
Neomake: eslint stdout: Basic configuration:
Neomake: eslint stdout:   -c, --config path::String   Use configuration from this file or shareable config
Neomake: eslint stdout:   --no-eslintrc               Disable use of configuration from .eslintrc
Neomake: eslint stdout:   --env [String]              Specify environments
Neomake: eslint stdout:   --ext [String]              Specify JavaScript file extensions - default: .js
Neomake: eslint stdout:   --global [String]           Define global variables
Neomake: eslint stdout:   --parser String             Specify the parser to be used
Neomake: eslint stdout:   --parser-options Object     Specify parser options
Ne
`

I have no idea what's going on because if I actually execute the command myself everything works fine but neomake seems to be having issues with it.

**Comment by theamazingfedex** [comment]
I'm sorry for any confusion, but eslint is not included with a neomake
install. Neomake tries to use eslint as the default maker, if you already
have it installed. Make sure you're on the most recent release of neomake
too.

**Comment by s-mage** [comment]
@thornycrackers I had the same problem. You should pass args like this: ` ['--config', '~/.eslint.js'] `

**Comment by thornycrackers** [comment]
@s-mage Thank you! I was able to make mine work with the following, in case someone else runs into this issue. 

`
autocmd! BufWritePost * Neomake
let g:neomake_javascript_enabled_makers = ['eslint']
let g:neomake_open_list = 1
let g:neomake_javascript_eslint_maker = {
    \ 'args': ['--no-color', '--format', 'compact', '--config', '~/.eslintrc.json'],
    \ 'errorformat': '%f: line %l\, col %c\, %m'
    \ }
`

The only issue I have now is that moving my cursor from the location window closes it but at least the errors show up, Thanks for the help!

**Comment by blueyed** [comment]
@s-mage @theamazingfedex 
Please provide a PR to get this fixed for everybody.

I've thought there was a PR already regarding this (related to different versions), but could not find it just now.

**Comment by ptn** [comment]
I ran into a similar problem, fixed with this https://github.com/neomake/neomake/issues/247#issuecomment-175808155

**Comment by blueyed** [comment]
@ptn 
So for you it was more an issue of not having the executable in `$PATH` then - which appears to be different (at least from other comments here), but a good thing to check of course.
(commented in https://github.com/neomake/neomake/issues/247#issuecomment-406775976 - let's keep it there).

**Comment by ptn** [comment]
Ah yeah yeah, I just thought I'd give others with the same problem a link to another solution, in case this one doesn't work. It's def different causes for similar symptoms.
