### ISSUE TITLE
How to change symbols

### ISSUE THREAD

**Issue by RenatoUtsch** [benekastah/neomake#306]
Hi,

How can I change Neomake's symbols that appear to the left of the line numbers? I want to make them more similar to syntastic's ones (red on error, etc).

**Comment by alexlafroscia** [comment]
Pretty sure you can set `g:neomake_error_sign` or `g:neomake_warning_sign` to change the symbol or highlight group used.

**Comment by RenatoUtsch** [comment]
Thanks!
