### ISSUE TITLE
g:neomake_make_modified sometimes leaves temp files laying around

### ISSUE THREAD

**Issue by benekastah** [benekastah/neomake#31]
Most of the time it cleans them up, but sometimes leaves them around. Probably need a good way to log errors to a file before tracking this down.

**Comment by Neki** [comment]
I found another situation that can trigger this bug: calling `:Neomake` (on a modified buffer), then quickly after `:wq` before the maker is finished.

**Comment by benekastah** [comment]
Ah, good point. We should also clean these files up in a `VimLeave` autocmd.

**Comment by benekastah** [comment]
Will close as wontfix if/when #84 gets merged.

**Comment by benekastah** [comment]
The make_modified feature was removed, so this issue is now invalid.
