### ISSUE TITLE
Neomake Location List toggles between open and closed on a single save

### ISSUE THREAD

**Issue by ddelnano** [benekastah/neomake#323]
I am currently using neomake for php and javascript projects.  Sometimes I run into the situation where on save (I run neomake on BufWritePost) the location list opens and closes indefinitely as shown in the gif below.
![neomake](https://cloud.githubusercontent.com/assets/5855593/13439152/44532666-dfba-11e5-9538-38b27efb019c.gif)

This is a single save and as long as the buffer has focus it continues to toggle like that.

I noticed that it happens on whitespace errors that get picked up by JSCS.  I am not sure if this is the only error that this happens on but it was the only one I am able to reproduce manually.

**Comment by theamazingfedex** [comment]
Go through your .vimrc and copy every line that says `neomake` and paste them into a code block in here so we can see what you have configured.

**Comment by ddelnano** [comment]
This file contains all my neomake config https://github.com/ddelnano/dotfiles/blob/master/vim/plugin_config/neomake.vim

**Comment by theamazingfedex** [comment]
Hmm, I'm not sure myself, as I've never used jscs AND eslint together, but hopefully someone else has and can help you out. 
In the mean-time as a work-around, I would suggest disabling the location list automatically opening, and just look for the gutter lines where you have errors. The error is shown in the command line, and if you want to see the whole list you should still be able to `:lopen`
Sorry I'm unable to provide a more elegant solution.

**Comment by theamazingfedex** [comment]
Also, what I do to make sure that I'm using my project specific, locally installed eslint, is this: 
`let g:eslint_path = system('PATH=$(npm bin):$PATH && which eslint')`
which loads the local npm bin onto the PATH, and asks for the path to the eslint exe, which if you have one locally, it will find first, and if not, it will default to a global installation.
And then:
`let g:neomake_javascript_eslint_exe=substitute(g:eslint_path, '^\n*\s*\(.\{-}\)\n*\s*$', '\1', '')`
loads that path into something neomake likes and sets the executable.

**Comment by ddelnano** [comment]
Yea I saw your comment on the previous issue and I will definitely try that out when I get the chance, currently at work and need my linting to work without issues right now :)

**Comment by dadgar** [comment]
I had this issue as well using the built in go makers

**Comment by ddelnano** [comment]
Did you ever get it resolved?

**Comment by dadgar** [comment]
Nope, this was as of yesterday

**Comment by ddelnano** [comment]
I need to dig into the source code but haven't had the chance since I've been busy.

**Comment by ddelnano** [comment]
My php and JSON linters work fine so I'm not sure what's going on. Do you have issues with other linters?

**Comment by nanzhong** [comment]
Why was this issue resolved? Did you find a solution @ddelnano? I'm having the same issue with go maker and the ruby rubocop maker.

**Comment by ddelnano** [comment]
The issue is not resolved.  I have just kind of dealt with it.  Very annoying but I have not had time to really dig into the source code at all.

**Comment by zbindenren** [comment]
same problem here with go

**Comment by nanzhong** [comment]
For ruby, I noticed that putting rubocop before mri in the list solved the problem for me.

Feels like something is wrong in the way the checkers are run asynchronously and communicate back, causing them to constantly get re-run.

**Comment by premjg** [comment]
I see a similar issue with Haskell (hlint, hdevtools and ghcmod).

**Comment by siemiatj** [comment]
hmm in my case it doesn't even show the list and closes it when I open it with :lopen . And I'm only using eslint.

**Comment by blueyed** [comment]
Be sure to not use `BufEnter` to call `Neomake` with `neomake_open_list != 0` (see #578).

**Comment by blueyed** [comment]
This is also what @ddelnano pasted: https://github.com/ddelnano/dotfiles/blob/master/vim/plugin_config/neomake.vim#L3-L6.

**Comment by theNotoriousHxc** [comment]
I had this problem just now, If you have another Autocommand listening for **BufEnter** then this may cause the problem.

I have this on my **~/.config/nvim/init.vim**

`    au BufEnter,BufWinEnter,CursorHold,CursorHoldI * : silent! checktime
`

So what causes the toggle is the previous command, it keeps executing **checktime**

So if what fixes the error for me is change this line:

`    autocmd! BufWritePost,BufEnter * Neomake
`

to

`
    autocmd! BufWritePost,BufReadPost * Neomake
`

Hope, this helps. :)
