### ISSUE TITLE
No support for Python2?

### ISSUE THREAD

**Issue by Ron89** [benekastah/neomake#340]
Is it intentional or Python2 support is dropped for neomake? Currently in
document I don't see how I can configure neomake to check grammar mistakes in
Python2 code.

**Comment by timfeirg** [comment]
it's actually covered in the docs, just search python inside the doc, [here](https://github.com/benekastah/neomake/blob/master/doc/neomake.txt#L196)

you can add `autocmd! BufWritePost * Neomake` in your vimrc to enable neomake for all filetypes, after write, and then you open up a `.py` file with neovim, `:w` and the error signs should show.

if still not working, could you verify that `neomake_python_enabled_makers` are installed on your system? like `pylint`, `pep8`?

**Comment by Ron89** [comment]
They are installed. Actually I have both python2 and python3's version installed. The problem is, when I invoke Neomake, only Python3 version's `pylint` is called. And I may get error message like `No () after print`, since I mainly code in Python2.7.

Syntastic actually specified an variable `g:syntastic_python_python_exec` for me to specify if it's Python2 or Python3 version I prefer. Yet I don't see equivalent variable here.

**Comment by Ron89** [comment]
I am using Arch linux, by the way. So by default, `python` in my system specifically mean `python3`. If I want to use `python2` I have to explicitely use command `python2` or `python2.7`. Hope this information helps.

**Comment by timfeirg** [comment]
it seems pylint may be installed through `pip3` rather than python2's `pip`? can you try to install pylint for python 2, perhaps, using `pip2` if it's on your system

**Comment by Ron89** [comment]
OK, I have installed `pylint` and `pylint2` on my system from Arch repository. I don't want to use `pip` to install them because I don't want conflicting command name mess up my root folder. 

Command `pylint --version` will return

    pylint 1.5.4, 
    astroid 1.4.4
    Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
    [GCC 5.3.0]

Command `pylint2 --version` will return

    pylint2 1.5.4, 
    astroid 1.4.4
    Python 2.7.11 (default, Mar  3 2016, 11:00:04) 
    [GCC 5.3.0]

I wonder if I should try adding `pylint2` into my `g:neomake_enabled_makers`. I didn't try because it generate error message in `syntastic`.

**Comment by ironhouzi** [comment]
Did you find a solution to this problem? I am in the exact same situation.

**Comment by Ron89** [comment]
No. Adding `pylint2` to `g:neomake_enabled_maker` will prompt error message:

    Error detected while processing function neomake#Make..<SNR>150_Make..neomake#GetMaker:
    line   41:
    E121: Undefined variable: maker
    E116: Invalid arguments for function deepcopy(maker)
    E15: Invalid expression: deepcopy(maker)

Or did I do something wrong? I mean, I see no instruction in your document on how to enable specifically Python2's syntax checking if both Python2 and Python3 are available on the machine. Or is it not implimented yet?

**Comment by hansrodtang** [comment]
There is no "pylint2" maker, so adding it the the list of enabled makers doesn't do anything useful. You would need to create a new maker named `pylint2` and place it in with the other makers.

The easiest solution to run `pylint2` instead of `pylint(3)` is probably:
```vim
let g:neomake_python_enabled_makers = ['pylint']
let g:neomake_python_pylint_exe = 'pylint2'
```

**Comment by Ron89** [comment]
Thanks, it works.
