### ISSUE TITLE
why not support c?

### ISSUE THREAD

**Issue by kdurant** [benekastah/neomake#35]
a lot of people use **C**

**Comment by benekastah** [comment]
I'm more than willing to support any language at all. The reason there is no support for c at this moment is that nobody who regularly uses it has added support for it yet. I will happily merge a pull request that adds c support. To do this, you will need to add a file at `autoload/neomake/makers/c.vim`. A good minimal example of what this file should look like can be found at [`autoload/neomake/makers/ruby.vim`](https://github.com/benekastah/neomake/blob/master/autoload/neomake/makers/ruby.vim). It might look roughly like this:

```
" vim: ts=4 sw=4 et

function! neomake#makers#c#EnabledMakers()
    return ['gcc']
endfunction

function! neomake#makers#c#gcc()
    return {
        \ 'args': ['-Wall', '{OTHER_ARGS_HERE}'],
        \ 'errorformat': '{REASONABLE_ERROR_FORMAT_HERE}'
        \ }
endfunction
```

Then you just fill in the blanks.

**Comment by benekastah** [comment]
I should also mention that if you want to get up and running quickly for yourself, you have a couple of options apart from modifying the plugin source code.

1. Set your `makeprg` and `errorformat` to whatever you use for c coding. If your `makeprg` can take a filename as an argument, then running `:Neomake` will just work. If it doesn't take an argument like that, you can run the command with no arguments in vim's current directory by running `:Neomake!` (note the exclamation point).

2. Set up a linter like this:

```
let g:neomake_c_enabled_makers = ['gcc']
let g:neomake_c_gcc_maker = {
    \ 'exe': 'gcc',
    \ 'errorformat': '{WHATEVER_YOU_USE}',
    \ 'args': ['{WHATEVER_YOU_USE}']
    \ }
```

And run it on a c file using `:Neomake!`. As long as the executable takes a single file as input and your errorformat is accurate, it should just work.

**Comment by benekastah** [comment]
#36 and #37 add c++ and c support respectively with clang.
