### ISSUE TITLE
Is it possible to [intentionally] toggle the :lopen window?

### ISSUE THREAD

**Issue by zhimsel** [benekastah/neomake#355]
I'd like to have a single keymap to open and close the :lopen window. For instance: 

If my map is `c-\`, I'd like it to run `:lopen`. However, if the :lopen window is already up, I'd like `c-\` to run `:lclose` instead. I know I could write a vimscript function to do that, but I'm not sure how to detect the window's state...

Are there any identifying variables or attributes of the window I could use?

Thanks!

**Comment by herrbischoff** [comment]
Check this out: https://github.com/milkypostman/vim-togglelist

**Comment by zhimsel** [comment]
Awesome, works great. Thanks!

I did google, but couldn't find anything near what I was looking for. Didn't realize the window was a vim feature, not a neomake feature.

**Comment by herrbischoff** [comment]
You're welcome. Next time you encounter something like this (yes, Vim *is* hard to figure out sometimes), search Vim's help: `:h <command>`, as in `:h :lopen`. The documentation is often forgotten about... ;)

**Comment by zhimsel** [comment]
I use :help all the time! :)

Didn't realize the :lopen command was vim's and not neomake's.


--
Zach Himsel
zach@himsel.net
http://zach.himsel.net
