### ISSUE TITLE
Can you be more specific how to set `makeprg` and `errorformat` to normal?

### ISSUE THREAD

**Issue by yifanchen** [benekastah/neomake#384]
When running `:Neomake`, nothing comes back.
When running `:Neomake!`, it says `Neomake: makeprg complete with exit code 2`. But nothing happens to my file, no warning, no error.

I tried all, `ESlint`, `JShint` and `JSCS`.

**Comment by yosemitebandit** [comment]
What versions of vim and neomake are you using?  I'm on neovim 0.1.3 and the latest version of this plugin.

I setup a little test file and installed jshint:

```
$ cat test.js
function test(a, b) {
	return a;
	return b;
}
$ npm install -g jshint
```

Then I opened `test.js` with neovim, ran `:Neomake` and jshint does indeed put an error in the gutter.  Maybe you have an old version of something?

Note that I didn't have to change `errorformat` or `makeprg` -- I also didn't have to setup any `Neomake` "makers."  It worked out of the box despite what the docs say.

**Comment by yifanchen** [comment]
Yeah, the problem I have before was I am trying to lint with Airbnb, now it works without Airbnb.
Thanks.
