### ISSUE TITLE
Improving shortcut-based navigation of errors: :lprev & :lnext won't work when there's a single error

### ISSUE THREAD

**Issue by brunal** [benekastah/neomake#44]
Hi,
Maybe I'm missing a clever way to do it but currently I have the following in my rc file:
```
nnoremap <Tab> :lnext<CR>
nnoremap <S-Tab>: lprev<CR>
```
It works fine enough when there are 2+ errors: first <tab> will bring me to the **second** error and I can navigate them all with <tag> or <shift>+<tab>. However this won't work when there is a single error, for we're initially on the first location (in the loc list, even if the culprit line is not displayed); and I find this behaviour highly annoying.

Am I missing a simple way to improve my workflow, or is that a real feature request?

**Comment by benekastah** [comment]
For this you can use :lfirst to go to the first error and :lnext/:lprev every time after that. As a plugin author, there's not really anything I could do about vim's behavior here, but for me :lfirst does the trick.

**Comment by brunal** [comment]
Nice, thank you for the tip! Would you happen to be aware of any way to bind <tab> to :lfirst on first press after a check, and :lnext on subsequent ones? (and symmetrically with :llast and :lprevious)

**Comment by benekastah** [comment]
That would be pretty tricky. The best I know how to do is have another key map for lfirst. Maybe <leader><Tab>?

**Comment by szymonkaliski** [comment]
not that complicated actually, here's what I'm using, could be better probably:

```vim
function! LocationNext()                                                                  
  try                                                                                     
    lnext                                                                                 
  catch                                                                                   
    try | lfirst | catch | endtry                                                         
  endtry                                                                                  
endfunction                                                                               

nnoremap <leader>e :call LocationNext()<cr> 
```

**Comment by brunal** [comment]
That works wonders, thank you a lot @szymonkaliski!!
