### ISSUE TITLE
neomake_make_modified causes error

### ISSUE THREAD

**Issue by cartolari** [benekastah/neomake#51]
When the option g:neomake_make_modified is set to 1 Neomake causes an error because it tries to invoke a function without the keyword call before, so vim understands it as a command.
The call keyword should be placed before the function invocation.
The line 212 of the file autoload/neomake.vim causes the error:
```vim
neomake#utils#LoudMessage('Neomake: wrote temp file '.makepath)
```
For me putting a call before the line solved the problem
```vim
call neomake#utils#LoudMessage('Neomake: wrote temp file '.makepath)
```

**Comment by benekastah** [comment]
Thanks for finding this! It would be awesome if you could submit a pull request for this, since I'm not sure if I'll have time to work on this today.
