### ISSUE TITLE
Warning when there is no checker available

### ISSUE THREAD

**Issue by cartolari** [benekastah/neomake#53]
Suppose I am editing a bash file and doesn't have shellcheck (the default enabled checker for shell script files), Neomake will warn me every time I save a file (because I've settled a autocommand for that because it's very convenient and maybe should be the default setting).
What about doing nothing when calling Neomake, and if the user wants to know what checkers are available and what  checkers are enabled a command named, maybe NeomakeInfo (pretty much like SyntasticInfo) could be called.
This way we can have the convenience to run the checkers automatically and there is no need to setup only to checkers available on a giving machine.
By not running the checkers if none are available and providing this function, I think would be more customization friendly.
What about this?

**Comment by benekastah** [comment]
If you are using a recent checkout, you shouldn't be getting any warning unless you've configured neomake to log everything. g:neomake_verbose should be 0 or 1 for most people. It's 1 by default. Can you update to the latest and verify your verbose setting value and let me know if it still happens?

The NeomakeInfo command sounds like a great idea and should be easy.

**Comment by cartolari** [comment]
The variable g:neomake_verbose wasn't set, also setting it to 0 does not stop Neomake of showing the message that no checker is installed.

**Comment by cartolari** [comment]
I figured it out, I don't know if it's a bug or a feature, but looking at the source code in autoload/neomake/utils.vim the function neomake#utils#LogMessage logs message which verbose is greater than or EQUAL to the log level, so for  Neomake do not report anything when it's called, the g:neomake_verbose variable should be set to a value lower than 0 namely -1.

**Comment by benekastah** [comment]
Actually, that warning was an error message, which I think is too high-priority. I changed it to a debug message, so you should be able to unset the `g:neomake_verbose` variable again. You can leave it the way it is if you want, but then you'll get no feedback from neomake, which could make it hard to figure out  what's going on if/when a problem arises.

**Comment by cartolari** [comment]
That's why I proposed the Neomakeinfo command, do you think it'll be useful, maybe I'll try a PR.

**Comment by benekastah** [comment]
Yeah, I think it's a good idea, I would be happy to take a PR for that. Currently you can get partway there by temporarily doing `let g:neomake_verbose = 3` and then running neomake again. Then you'll get all the debug messages, which should help you figure out what is going on.
