### ISSUE TITLE
Some kind of configurable gutter symbols

### ISSUE THREAD

**Issue by trusktr** [benekastah/neomake#56]
would be nice.

In the simple case, it might be something like

```
let g:neomake_javascript_jshint_maker = {
    \ 'args': ['--verbose'],
    \ 'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)',
    \ 'gutter_symbol': '✖',
    \ }
let g:neomake_javascript_enabled_makers = ['jshint']
```

and it'd be shown on lines corresponding to the `%l` in the errors.

**Comment by benekastah** [comment]
Having gutter symbols configurable by maker is an interesting idea, but I think it would overcomplicate the code that places signs. I need to fix a lot of stuff up there so when I'm done doing that I can revisit this idea. In case you weren't aware, you do have some control over neomake's signs: check out `:help g:neomake_error_sign`.
