### ISSUE TITLE
AddExprCallback: not possible to change sign neomake_err

### ISSUE THREAD

**Issue by Neki** [benekastah/neomake#60]
I am currently working on a Ruby file (checkers : mri + rubocop on JRuby). If I call `:Neomake` on this file, I get the error:

```
Error detected while processing function neomake#ProcessCurrentBuffer..<SNR>125_ProcessJobOutput..<SNR>125_AddExprCallback:
line   38:
E885: Not possible to change sign neomake_err
```

I then get this error every time I enter the window displaying my buffer. If I restart Vim (without loading a session), and call `:Neomake` again, I get the exact same error.

The corresponding part of the logfile generated by neomake:
```
2015-03-13T21:45:32+0100 Log level 2: Neomake: Starting: ruby -c -T1 -w lib/remotebox/core/world.rb
2015-03-13T21:45:32+0100 Log level 2: Neomake: Starting: rubocop --format emacs lib/remotebox/core/world.rb
2015-03-13T21:45:36+0100 Log level 3: Neomake: mri stderr: SyntaxError in lib/remotebox/core/world.rb:73: syntax error, unexpected kRESCUE
2015-03-13T21:45:36+0100 Log level 3: Neomake: mri stderr:         rescue UnsupportedSystem => e
2015-03-13T21:45:36+0100 Log level 3: Neomake: mri stderr:               ^
2015-03-13T21:45:36+0100 Log level 3: Neomake: mri stderr done.
2015-03-13T21:45:36+0100 Log level 3: Neomake: mri processing 3 lines of output
2015-03-13T21:45:36+0100 Log level 3: Neomake: executing: sign place buffer=5
2015-03-13T21:45:36+0100 Log level 3: Neomake: mri stderr: 
2015-03-13T21:45:36+0100 Log level 3: Neomake: mri stderr: 
2015-03-13T21:45:36+0100 Log level 3: Neomake: mri stderr done.
2015-03-13T21:45:36+0100 Log level 3: Neomake: mri processing 2 lines of output
2015-03-13T21:45:36+0100 Log level 1: Neomake: mri complete
2015-03-13T21:45:41+0100 Log level 3: Neomake: rubocop stdout: /media/docs/projects/remotebox/lib/remotebox/core/world.rb:73:9: E: unexpected token kRESCUE
2015-03-13T21:45:41+0100 Log level 3: Neomake: rubocop stdout: 
2015-03-13T21:45:41+0100 Log level 3: Neomake: rubocop stdout done.
2015-03-13T21:45:41+0100 Log level 3: Neomake: rubocop processing 2 lines of output
2015-03-13T21:45:41+0100 Log level 3: Neomake: executing: sign place buffer=4
2015-03-13T21:49:01+0100 Log level 1: Neomake: rubocop complete
2015-03-13T21:49:04+0100 Log level 3: Neomake: rubocop processing 2 lines of output
2015-03-13T21:49:04+0100 Log level 3: Neomake: executing: sign place buffer=4
2015-03-13T21:49:04+0100 Log level 3: Neomake: rubocop processing 2 lines of output
2015-03-13T21:49:04+0100 Log level 3: Neomake: executing: sign place buffer=4
```

I am using [gitgutter](https://github.com/airblade/vim-gitgutter) which places signs in the gutter before `:Neomake` is called, see:

![image](https://cloud.githubusercontent.com/assets/2143664/6647111/6ff4bf74-c9cb-11e4-9fde-3810d708df03.png)

gitgutter had already set signs in front of the lines where neomake should have placed signs. Neomake manages to place an error sign on a line where gitgutter did not place a sign.

Unfortunately I can not share the whole file I am working on.

Using the latest master to date: 1d45725c1f3c6b2c72d724b5a9f446e6bb376afc, on Neovim neovim/neovim@032c20078a617252ff9fc5ac03b4c390a6868a4d

**Comment by Neki** [comment]
I managed to narrow down the issue.

First, disabling gitgutter does not fix the issue.

With the default configuration of Neomake for Ruby (makers MRI + rubocop), create a new Ruby file (`set filetype=ruby`) and type in some syntactically invalid Ruby code e.g
```ruby
if if end
```

then saving and calling :Neomake will produce the error.

I suspect that this error happens when two checkers for the same file produce a message for the same line (which will happen a lot with MRI + rubocop since both detect syntax errors).

**Comment by benekastah** [comment]
Thanks for reporting, I'll have a look this weekend.

**Comment by benekastah** [comment]
Oh, and please post your neovim version as well.

**Comment by Neki** [comment]
I can confirm than setting either `let g:neomake_ruby_enabled_makers = ['rubocop']` or `let g:neomake_ruby_enabled_makers = ['mri']` fixes the issue.

**Comment by Neki** [comment]
I am using the latest Neovim, please see the end of my first message.

**Comment by benekastah** [comment]
Btw, I did start on this last weekend but ended up tracking down a neovim bug the whole time :(

**Comment by benekastah** [comment]
I said I fixed this in #77. Let me know if you get this again.

**Comment by Neki** [comment]
Thanks! It does fix the situation I am describing here.

**Comment by gblock0** [comment]
I'm getting a similar error in MacVim (version 7.4.769), but it works fine in neovim (NVIM 0.0.0-alpha+201508151511 (compiled Aug 16 2015 10:34:38)

Not sure if this is the same, if not I can open a new issue.

![screen shot 2015-10-31 at 17 50 53](https://cloud.githubusercontent.com/assets/1434705/10866341/131a302a-7ff8-11e5-9d28-c6b74f362acf.png)

I am trying to check a javascript file. This is what my neomake config is:

```
autocmd! BufWritePost * Neomake

let g:neomake_javascript_jshint_maker = {
    \ 'args': ['--verbose'],
    \ 'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)',
		\ }
let g:neomake_javascript_enabled_markers = ['jshint', 'jscs']
let g:neomake_open_list = 1
```

**Comment by benekastah** [comment]
This is probably related to the fact that macvim checks the file synchronously and neovim does it asynchronously. So, I do think it is a different bug. Could you please file a separate issue?

**Comment by gblock0** [comment]
Yep, will do.

**Comment by benjie** [comment]
This issue might have resurfaced. I'm using eslint and flow makers and if I make a syntax error I get this every time I move the cursor:

```
Error detected while processing function neomake#CursorMoved[4]..neomake#signs#PlaceVisibleSigns[10]..neomake#signs#PlaceSign:
line   34:
E885: Not possible to change sign neomake_err
Press ENTER or type command to continue
```

To fix I can just go to a single maker and then re-save the file:

```
:let g:neomake_javascript_enabled_makers=['eslint']
:w
```

**Comment by blueyed** [comment]
@benjie 
Please create a new issue, with steps to reproduce it - follow the issue template.

**Comment by benjie** [comment]
```
:version
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/build/conf
ig -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/src -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-50
51-avofzl/neovim-0.1.5/deps-build/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/build/src/nvim/auto -I/tmp/neovim-20160826-5051-avofzl/neovim-0.1.5/build/include
Compiled by benjie@computer.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.5/share/nvim"

Press ENTER or type command to continue
```
Running neomake 2abd3f0ead6f8b66fb85004a5401a103818c204e:

```
$ pwd
/Users/benjie/.vim/plugged/neomake
$ git rev-parse HEAD
2abd3f0ead6f8b66fb85004a5401a103818c204e
```

**Comment by blueyed** [comment]
@benjie 
That is not enough information, and also not a separate issue.

**Comment by benjie** [comment]
@blueyed Sorry, I posted the above comment without seeing your reply whilst reading back through this thread (wasn't aware you'd replied until now). I'll file an issue once I have the relevant information 👍
