### ISSUE TITLE
Statusline not counting lowercase "w" and "e"

### ISSUE THREAD

**Issue by yyt16384** [benekastah/neomake#71]
Some makers produce lowercase "w" and "e" in their error messages (at lease gcc and clang on my machine), and they are not counted in statusline.

**Comment by benekastah** [comment]
This should be easy enough to fix.

**Comment by benekastah** [comment]
Let me know if it isn't fixed for you.

**Comment by yyt16384** [comment]
Thanks. It works fine now.
