### ISSUE TITLE
g:neomake_make_modified is not compatible with all checkers

### ISSUE THREAD

**Issue by Neki** [benekastah/neomake#73]
In some languages, the file name (and directory structure) is significant. For instance, Java requires the class "org.company.MyClass" to be defined in a file at `org/company/MyClass.java`. The same goes for Haskell (ghc-mod will refuse to check a file whose name does not end in `.hs` or `.lhs`, and I am pretty sure that messing with the Haskell naming conventions will break some tools), Python, and probably a lot of other languages.

When `g:neomake_make_modified` is set to 1, the name of the file that is actually checked does not (and can not) follow these rules, and thus the "run make on modified buffers" feature will simply not work. I verified this with the ghc-mod checker for Haskell, that simply outputs to stderr `ghc-mod: target src/Test.hs.1605.neomake.tmp is not a module name or a source file`.

I can foresee other sources of issues: checkers that can only check a whole project at once, issues if `:Neomake` and `:Neomake!` were to be run concurrently...

I see two options:
* dropping this feature altogether (the above is the reason why Syntastic does not support it, see scrooloose/syntastic#1034 for instance). This is my personal preference, I think this feature is too much trouble for little benefit.
* have checkers explicitly declare that they support this feature, which is still feasible at this point since there are not a lot of checkers.

Thoughts ?

**Comment by benekastah** [comment]
I think dropping the feature is probably the best course, too. @dpavlic asked for this feature in #28. Are you still using this feature?

**Comment by blueyed** [comment]
See https://github.com/neomake/neomake/pull/1057 for bringing it back.
