### ISSUE TITLE
Neomake error on rust file.

### ISSUE THREAD

**Issue by norcalli** [benekastah/neomake#81]
```
Error detected while processing function <SNR>183_NeomakeCommand..neomake#Make..neomake#MakeJob..<SNR>184_JobStart:
line   13:
E474: Invalid argument
```

**Comment by benekastah** [comment]
What version of neovim are you using? I'm guessing you need a more recent build. From the [readme](https://github.com/benekastah/neomake/blob/master/README.md):

> The minimum Neovim version supported by Neomake is NVIM 0.0.0-alpha+201503292107 (commit 960b9108c).

Let me know if that's not the issue.

**Comment by norcalli** [comment]
You were indeed correct. I was lagging on tarruda's branch. However, now I'm getting
```
error: couldn't read "%": No such file or directory (os error 2)
```

Seems to suggest something is being quoted unnecessarily. Side question while you're here if I can: is cargo support possible?

**Comment by benekastah** [comment]
With regards to your error, it would be helpful to know what maker you're running and a sample file that can reproduce the problem. We do have a cargo maker, which you can use by running `:Neomake! cargo` (note the exclamation point). This maker doesn't work on a single file at a time, but rather works on the whole project.

**Comment by benekastah** [comment]
#68 probably fixed your issue. Reopen this if you are still having trouble.
