### ISSUE TITLE
Placing Neomake's signs on top doesn't always work

### ISSUE THREAD

**Issue by benekastah** [benekastah/neomake#82]
We have [some code](https://github.com/benekastah/neomake/blob/ab12b5e0a8f575d85664e025087cd58e79ac91fc/autoload/neomake/signs.vim#L94) that attempts to place neomake's signs on top. For some reason, it doesn't always appear to work. I notice the issue while using [gitgutter](https://github.com/airblade/vim-gitgutter).

**Comment by languitar** [comment]
I can confirm this with gitgutter.
