### ISSUE TITLE
`E216: No such group or event: JobActivity neomake* call neomake#MakeHandler()` with current neovim

### ISSUE THREAD

**Issue by brendanjerwin** [benekastah/neomake#86]
It seems `JobActivity` was removed.

https://gitter.im/neovim/neovim?at=55244c41957202672d44c14a

**Comment by brendanjerwin** [comment]
WTH? I searched. I see this is a duplicate now.

**Comment by alxndr** [comment]
(It is a duplicate of #74, should be fixed by #75.)
