### ISSUE TITLE
Neomake does not work in non english locale

### ISSUE THREAD

**Issue by ptrendx** [benekastah/neomake#96]
Hi, 

I tried to use Neomake inside Neovim but it failed inside GetSigns functions saying it can't find variable fname. It turns out that inside signs_txt variable you are searching for specific english string: 'Signs for \(.*\):', and also depend on line being called "line" in result dictionary. As it turns out this is not the case if the locale is set to non english value. I made this quick workaround to change vim language of messages to english and then return back to previous locale:
```
diff --git a/autoload/neomake/signs.vim b/autoload/neomake/signs.vim
index 7e593aa..f016dae 100644
--- a/autoload/neomake/signs.vim
+++ b/autoload/neomake/signs.vim
@@ -29,7 +29,10 @@ function! neomake#signs#GetSigns(...) abort
         endif
     endfor
     call neomake#utils#DebugMessage('executing: '.place_cmd)
+    let curlang=v:lang
+    language en_US.utf8
     redir => signs_txt | silent exe place_cmd | redir END
+    silent exe "language ".curlang
     let fname_pattern = 'Signs for \(.*\):'
     for s in split(signs_txt, '\n')
         if s =~# fname_pattern
```
Unfortunately I am not experienced in VimScript nor in writing Vim plugins so I do not know if this is acceptable solution.

**Comment by benekastah** [comment]
This looks good to me. Would you mind submitting this as a pull request?
