### ISSUE TITLE
E197: Cannot set language to "en_US.utf8"

### ISSUE THREAD

**Issue by renstrom** [benekastah/neomake#99]
I don't enough about this locale business, but, basically this doesn't work:

    :language messages en_US.utf8
    E197: Cannot set language to "en_US.utf8"

But this works (note the capital "UTF-8"):

    :language messages en_US.UTF-8

I guess its related to https://github.com/benekastah/neomake/issues/96 and/or https://github.com/benekastah/neomake/pull/98.

OS X 10.10.3

**Comment by renstrom** [comment]
```bash
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by yyt16384** [comment]
I don't have much knowledge about locales, but I think maybe some systems accept one as an alias while some don't. Just looked into vim runtime files and those folders are using capital `UTF-8`, so I think it may be the standard. Better just use the capital one in code I think.

**Comment by benekastah** [comment]
@renstrom Please let me know if this fixes the issue for you.

**Comment by renstrom** [comment]
@benekastah Unfortunately no. I only now noticed that there was also missing a dash `-` between UTF and 8:

```diff
-:language messages en_US.UTF8
+:language messages en_US.UTF-8
```

Seems like OS X/iTerm2/zsh is rather pick about this.
